// Package platformapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package platformapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for RegisterProtocolDependencyInputBodyFormat.
const (
	RegisterProtocolDependencyInputBodyFormatGrpc    RegisterProtocolDependencyInputBodyFormat = "grpc"
	RegisterProtocolDependencyInputBodyFormatOpenapi RegisterProtocolDependencyInputBodyFormat = "openapi"
)

// Valid indicates whether the value is a known member of the RegisterProtocolDependencyInputBodyFormat enum.
func (e RegisterProtocolDependencyInputBodyFormat) Valid() bool {
	switch e {
	case RegisterProtocolDependencyInputBodyFormatGrpc:
		return true
	case RegisterProtocolDependencyInputBodyFormatOpenapi:
		return true
	default:
		return false
	}
}

// Defines values for CheckProtocolCompatibilityParamsFormat.
const (
	CheckProtocolCompatibilityParamsFormatGrpc    CheckProtocolCompatibilityParamsFormat = "grpc"
	CheckProtocolCompatibilityParamsFormatOpenapi CheckProtocolCompatibilityParamsFormat = "openapi"
)

// Valid indicates whether the value is a known member of the CheckProtocolCompatibilityParamsFormat enum.
func (e CheckProtocolCompatibilityParamsFormat) Valid() bool {
	switch e {
	case CheckProtocolCompatibilityParamsFormatGrpc:
		return true
	case CheckProtocolCompatibilityParamsFormatOpenapi:
		return true
	default:
		return false
	}
}

// Defines values for PublishProtocolParamsFormat.
const (
	PublishProtocolParamsFormatGrpc    PublishProtocolParamsFormat = "grpc"
	PublishProtocolParamsFormatOpenapi PublishProtocolParamsFormat = "openapi"
)

// Valid indicates whether the value is a known member of the PublishProtocolParamsFormat enum.
func (e PublishProtocolParamsFormat) Valid() bool {
	switch e {
	case PublishProtocolParamsFormatGrpc:
		return true
	case PublishProtocolParamsFormatOpenapi:
		return true
	default:
		return false
	}
}

// CompatibilityChangeResponse defines model for CompatibilityChangeResponse.
type CompatibilityChangeResponse struct {
	Breaking    bool    `json:"breaking"`
	Description string  `json:"description"`
	Kind        string  `json:"kind"`
	Operation   *string `json:"operation,omitempty"`
}

// CompatibilityReportResponse defines model for CompatibilityReportResponse.
type CompatibilityReportResponse struct {
	// Schema A URL to the JSON Schema for this object.
	//
	// Examples: https://api.paas.traumtech.ru/schemas/CompatibilityReportResponse.json
	Schema    *string                         `json:"$schema,omitempty"`
	Breaking  bool                            `json:"breaking"`
	Consumers []ConsumerCompatibilityResponse `json:"consumers"`
}

// ConsumerCompatibilityResponse defines model for ConsumerCompatibilityResponse.
type ConsumerCompatibilityResponse struct {
	Breaking              bool                          `json:"breaking"`
	Changes               []CompatibilityChangeResponse `json:"changes"`
	Comparable            bool                          `json:"comparable"`
	ConsumerServiceId     openapi_types.UUID            `json:"consumer_service_id"`
	ConsumerServiceName   string                        `json:"consumer_service_name"`
	ConsumerVersionId     openapi_types.UUID            `json:"consumer_version_id"`
	ConsumerVersionNumber int64                         `json:"consumer_version_number"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Location Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	Location *string `json:"location,omitempty"`

	// Message Error message text
	Message *string `json:"message,omitempty"`

	// Value The value at the given location
	Value interface{} `json:"value,omitempty"`
}

// ErrorModel defines model for ErrorModel.
type ErrorModel struct {
	// Schema A URL to the JSON Schema for this object.
	//
	// Examples: https://api.paas.traumtech.ru/schemas/ErrorModel.json
	Schema *string `json:"$schema,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	//
	// Examples: Property foo is required but is missing.
	Detail *string `json:"detail,omitempty"`

	// Errors Optional list of individual error details
	Errors *[]ErrorDetail `json:"errors,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	//
	// Examples: https://example.com/error-log/abc123
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	//
	// Examples: 400
	Status *int64 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	//
	// Examples: Bad Request
	Title *string `json:"title,omitempty"`

	// Type A URI reference to human-readable documentation for the error.
	//
	// Examples: https://example.com/errors/example
	Type *string `json:"type,omitempty"`
}

// ProtocolDependencyResponse defines model for ProtocolDependencyResponse.
type ProtocolDependencyResponse struct {
	// Schema A URL to the JSON Schema for this object.
	//
	// Examples: https://api.paas.traumtech.ru/schemas/ProtocolDependencyResponse.json
	Schema            *string            `json:"$schema,omitempty"`
	ConsumerServiceId openapi_types.UUID `json:"consumer_service_id"`
	ConsumerVersionId openapi_types.UUID `json:"consumer_version_id"`
	Format            string             `json:"format"`
	Id                openapi_types.UUID `json:"id"`
	Methods           []string           `json:"methods"`
	ProducerServiceId openapi_types.UUID `json:"producer_service_id"`
	RegisteredAt      time.Time          `json:"registered_at"`
	WaivedAttributes  []string           `json:"waived_attributes"`
}

// ProtocolPublishedResponse defines model for ProtocolPublishedResponse.
type ProtocolPublishedResponse struct {
	// Schema A URL to the JSON Schema for this object.
	//
	// Examples: https://api.paas.traumtech.ru/schemas/ProtocolPublishedResponse.json
	Schema    *string                         `json:"$schema,omitempty"`
	Breaking  bool                            `json:"breaking"`
	Consumers []ConsumerCompatibilityResponse `json:"consumers"`
	Protocol  *ProtocolResponse               `json:"protocol,omitempty"`
	Published bool                            `json:"published"`
}

// ProtocolResponse defines model for ProtocolResponse.
type ProtocolResponse struct {
	Format        string             `json:"format"`
	Name          string             `json:"name"`
	PublishedAt   time.Time          `json:"published_at"`
	ServiceId     openapi_types.UUID `json:"service_id"`
	VersionId     openapi_types.UUID `json:"version_id"`
	VersionNumber int64              `json:"version_number"`
}

// ProtocolView defines model for ProtocolView.
type ProtocolView struct {
	// Schema A URL to the JSON Schema for this object.
	//
	// Examples: https://api.paas.traumtech.ru/schemas/ProtocolView.json
	Schema           *string                 `json:"$schema,omitempty"`
	Document         *map[string]interface{} `json:"document,omitempty"`
	DocumentText     *string                 `json:"document_text,omitempty"`
	Format           *string                 `json:"format,omitempty"`
	Name             *string                 `json:"name,omitempty"`
	NarrowingSkipped *bool                   `json:"narrowing_skipped,omitempty"`
	Published        bool                    `json:"published"`
	PublishedAt      *time.Time              `json:"published_at,omitempty"`
	ServiceId        openapi_types.UUID      `json:"service_id"`
	VersionId        *openapi_types.UUID     `json:"version_id,omitempty"`
	VersionNumber    *int64                  `json:"version_number,omitempty"`
}

// PublishVersionInputBody defines model for PublishVersionInputBody.
type PublishVersionInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	//
	// Examples: https://api.paas.traumtech.ru/schemas/PublishVersionInputBody.json
	Schema *string `json:"$schema,omitempty"`

	// CommitRevision Идентификатор коммита
	CommitRevision string `json:"commit_revision"`
}

// RegisterProtocolDependencyInputBody defines model for RegisterProtocolDependencyInputBody.
type RegisterProtocolDependencyInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	//
	// Examples: https://api.paas.traumtech.ru/schemas/RegisterProtocolDependencyInputBody.json
	Schema *string `json:"$schema,omitempty"`

	// Document Снимок контракта продьюсера: OpenAPI — JSON-объект, gRPC — строка с .proto-исходником
	Document interface{} `json:"document"`

	// Format Формат снимка (пусто — openapi)
	Format *RegisterProtocolDependencyInputBodyFormat `json:"format,omitempty"`

	// Methods Используемые методы продьюсера: HTTP-паттерн ("GET /services/{id}") у OpenAPI, package.Service/Method у gRPC; пусто — зависимость от всего снимка
	Methods *[]string `json:"methods,omitempty"`

	// ProducerServiceId ID сервиса, на контракте которого собрана версия
	ProducerServiceId openapi_types.UUID `json:"producer_service_id"`

	// SupersedePrevious Снять зависимости прочих версий этого потребителя от того же продьюсера, оставив только регистрируемую (по умолчанию нет)
	SupersedePrevious *bool `json:"supersede_previous,omitempty"`

	// WaivedAttributes Атрибуты продьюсера, от которых потребитель отказался: "полное.имя.Типа.поле", у вокабуляра — "полное.имя.Типа.ЗНАЧЕНИЕ"; пусто — зависимость от всех атрибутов используемых методов
	WaivedAttributes *[]string `json:"waived_attributes,omitempty"`
}

// RegisterProtocolDependencyInputBodyFormat Формат снимка (пусто — openapi)
type RegisterProtocolDependencyInputBodyFormat string

// ServiceResponse defines model for ServiceResponse.
type ServiceResponse struct {
	// Schema A URL to the JSON Schema for this object.
	//
	// Examples: https://api.paas.traumtech.ru/schemas/ServiceResponse.json
	Schema    *string            `json:"$schema,omitempty"`
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	RepoUrl   *string            `json:"repo_url,omitempty"`
}

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// Schema A URL to the JSON Schema for this object.
	//
	// Examples: https://api.paas.traumtech.ru/schemas/VersionResponse.json
	Schema         *string            `json:"$schema,omitempty"`
	CommitRevision string             `json:"commit_revision"`
	CreatedAt      time.Time          `json:"created_at"`
	Id             openapi_types.UUID `json:"id"`
	Number         int64              `json:"number"`
}

// ListServicesParams defines parameters for ListServices.
type ListServicesParams struct {
	// Name Фильтр по имени сервиса (точное совпадение); можно повторять — вернутся все совпавшие. Пусто — весь перечень
	Name *[]string `form:"name,omitempty" json:"name,omitempty"`
}

// GetProtocolParams defines parameters for GetProtocol.
type GetProtocolParams struct {
	// Name Имя (alias) протокола; пусто — протокол по умолчанию
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Methods Оставить в контракте только эти методы ("МЕТОД /путь" у OpenAPI); пусто — контракт целиком
	Methods *[]string `form:"methods,omitempty" json:"methods,omitempty"`
}

// CheckProtocolCompatibilityJSONBody defines parameters for CheckProtocolCompatibility.
type CheckProtocolCompatibilityJSONBody = interface{}

// CheckProtocolCompatibilityParams defines parameters for CheckProtocolCompatibility.
type CheckProtocolCompatibilityParams struct {
	// Format Формат контракта-кандидата
	Format *CheckProtocolCompatibilityParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// CheckProtocolCompatibilityParamsFormat defines parameters for CheckProtocolCompatibility.
type CheckProtocolCompatibilityParamsFormat string

// PublishProtocolJSONBody defines parameters for PublishProtocol.
type PublishProtocolJSONBody = interface{}

// PublishProtocolParams defines parameters for PublishProtocol.
type PublishProtocolParams struct {
	// Format Формат протокола
	Format *PublishProtocolParamsFormat `form:"format,omitempty" json:"format,omitempty"`

	// Name Имя (alias) протокола; пусто — имя по умолчанию
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// PublishProtocolParamsFormat defines parameters for PublishProtocol.
type PublishProtocolParamsFormat string

// CheckProtocolCompatibilityJSONRequestBody defines body for CheckProtocolCompatibility for application/json ContentType.
type CheckProtocolCompatibilityJSONRequestBody = CheckProtocolCompatibilityJSONBody

// PublishVersionJSONRequestBody defines body for PublishVersion for application/json ContentType.
type PublishVersionJSONRequestBody = PublishVersionInputBody

// RegisterProtocolDependencyJSONRequestBody defines body for RegisterProtocolDependency for application/json ContentType.
type RegisterProtocolDependencyJSONRequestBody = RegisterProtocolDependencyInputBody

// PublishProtocolJSONRequestBody defines body for PublishProtocol for application/json ContentType.
type PublishProtocolJSONRequestBody = PublishProtocolJSONBody

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ListServices Список сервисов
	//
	// Corresponds with GET /services (the `ListServices` operationId).
	ListServices(ctx context.Context, params *ListServicesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetService Получить сервис по ID
	//
	// Corresponds with GET /services/{id} (the `GetService` operationId).
	GetService(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProtocol Получить протокол сервиса
	//
	// Corresponds with GET /services/{id}/protocol (the `GetProtocol` operationId).
	GetProtocol(ctx context.Context, id openapi_types.UUID, params *GetProtocolParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CheckProtocolCompatibilityWithBody Проверить совместимость контракта-кандидата с потребителями
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /services/{id}/protocol/compatibility (the `CheckProtocolCompatibility` operationId).
	CheckProtocolCompatibilityWithBody(ctx context.Context, id openapi_types.UUID, params *CheckProtocolCompatibilityParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CheckProtocolCompatibility Проверить совместимость контракта-кандидата с потребителями
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /services/{id}/protocol/compatibility (the `CheckProtocolCompatibility` operationId).
	CheckProtocolCompatibility(ctx context.Context, id openapi_types.UUID, params *CheckProtocolCompatibilityParams, body CheckProtocolCompatibilityJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PublishVersionWithBody Опубликовать версию сервиса
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /services/{id}/versions (the `PublishVersion` operationId).
	PublishVersionWithBody(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PublishVersion Опубликовать версию сервиса
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /services/{id}/versions (the `PublishVersion` operationId).
	PublishVersion(ctx context.Context, id openapi_types.UUID, body PublishVersionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RegisterProtocolDependencyWithBody Зарегистрировать зависимость версии от контракта другого сервиса
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /services/{id}/versions/{version_id}/dependencies (the `RegisterProtocolDependency` operationId).
	RegisterProtocolDependencyWithBody(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RegisterProtocolDependency Зарегистрировать зависимость версии от контракта другого сервиса
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /services/{id}/versions/{version_id}/dependencies (the `RegisterProtocolDependency` operationId).
	RegisterProtocolDependency(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, body RegisterProtocolDependencyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PublishProtocolWithBody Опубликовать протокол версии сервиса
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /services/{id}/versions/{version_id}/protocol (the `PublishProtocol` operationId).
	PublishProtocolWithBody(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, params *PublishProtocolParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PublishProtocol Опубликовать протокол версии сервиса
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /services/{id}/versions/{version_id}/protocol (the `PublishProtocol` operationId).
	PublishProtocol(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, params *PublishProtocolParams, body PublishProtocolJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListServices Список сервисов
//
// Corresponds with GET /services (the `ListServices` operationId).
func (c *Client) ListServices(ctx context.Context, params *ListServicesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListServicesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetService Получить сервис по ID
//
// Corresponds with GET /services/{id} (the `GetService` operationId).
func (c *Client) GetService(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetServiceRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetProtocol Получить протокол сервиса
//
// Corresponds with GET /services/{id}/protocol (the `GetProtocol` operationId).
func (c *Client) GetProtocol(ctx context.Context, id openapi_types.UUID, params *GetProtocolParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProtocolRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CheckProtocolCompatibilityWithBody Проверить совместимость контракта-кандидата с потребителями
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /services/{id}/protocol/compatibility (the `CheckProtocolCompatibility` operationId).
func (c *Client) CheckProtocolCompatibilityWithBody(ctx context.Context, id openapi_types.UUID, params *CheckProtocolCompatibilityParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCheckProtocolCompatibilityRequestWithBody(c.Server, id, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CheckProtocolCompatibility Проверить совместимость контракта-кандидата с потребителями
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /services/{id}/protocol/compatibility (the `CheckProtocolCompatibility` operationId).
func (c *Client) CheckProtocolCompatibility(ctx context.Context, id openapi_types.UUID, params *CheckProtocolCompatibilityParams, body CheckProtocolCompatibilityJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCheckProtocolCompatibilityRequest(c.Server, id, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PublishVersionWithBody Опубликовать версию сервиса
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /services/{id}/versions (the `PublishVersion` operationId).
func (c *Client) PublishVersionWithBody(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublishVersionRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PublishVersion Опубликовать версию сервиса
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /services/{id}/versions (the `PublishVersion` operationId).
func (c *Client) PublishVersion(ctx context.Context, id openapi_types.UUID, body PublishVersionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublishVersionRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RegisterProtocolDependencyWithBody Зарегистрировать зависимость версии от контракта другого сервиса
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /services/{id}/versions/{version_id}/dependencies (the `RegisterProtocolDependency` operationId).
func (c *Client) RegisterProtocolDependencyWithBody(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterProtocolDependencyRequestWithBody(c.Server, id, versionId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RegisterProtocolDependency Зарегистрировать зависимость версии от контракта другого сервиса
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /services/{id}/versions/{version_id}/dependencies (the `RegisterProtocolDependency` operationId).
func (c *Client) RegisterProtocolDependency(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, body RegisterProtocolDependencyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterProtocolDependencyRequest(c.Server, id, versionId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PublishProtocolWithBody Опубликовать протокол версии сервиса
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /services/{id}/versions/{version_id}/protocol (the `PublishProtocol` operationId).
func (c *Client) PublishProtocolWithBody(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, params *PublishProtocolParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublishProtocolRequestWithBody(c.Server, id, versionId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PublishProtocol Опубликовать протокол версии сервиса
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /services/{id}/versions/{version_id}/protocol (the `PublishProtocol` operationId).
func (c *Client) PublishProtocol(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, params *PublishProtocolParams, body PublishProtocolJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublishProtocolRequest(c.Server, id, versionId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListServicesRequest constructs an http.Request for the ListServices method
func NewListServicesRequest(server string, params *ListServicesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/services")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Name != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "name", *params.Name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetServiceRequest constructs an http.Request for the GetService method
func NewGetServiceRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/services/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetProtocolRequest constructs an http.Request for the GetProtocol method
func NewGetProtocolRequest(server string, id openapi_types.UUID, params *GetProtocolParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/services/%s/protocol", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Name != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "name", *params.Name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Methods != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "methods", *params.Methods, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCheckProtocolCompatibilityRequest calls the generic CheckProtocolCompatibility builder with application/json body
func NewCheckProtocolCompatibilityRequest(server string, id openapi_types.UUID, params *CheckProtocolCompatibilityParams, body CheckProtocolCompatibilityJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCheckProtocolCompatibilityRequestWithBody(server, id, params, "application/json", bodyReader)
}

// NewCheckProtocolCompatibilityRequestWithBody constructs an http.Request for the CheckProtocolCompatibility method, with any body, and a specified content type
func NewCheckProtocolCompatibilityRequestWithBody(server string, id openapi_types.UUID, params *CheckProtocolCompatibilityParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/services/%s/protocol/compatibility", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Format != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "format", *params.Format, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPublishVersionRequest calls the generic PublishVersion builder with application/json body
func NewPublishVersionRequest(server string, id openapi_types.UUID, body PublishVersionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPublishVersionRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPublishVersionRequestWithBody constructs an http.Request for the PublishVersion method, with any body, and a specified content type
func NewPublishVersionRequestWithBody(server string, id openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/services/%s/versions", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRegisterProtocolDependencyRequest calls the generic RegisterProtocolDependency builder with application/json body
func NewRegisterProtocolDependencyRequest(server string, id openapi_types.UUID, versionId openapi_types.UUID, body RegisterProtocolDependencyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRegisterProtocolDependencyRequestWithBody(server, id, versionId, "application/json", bodyReader)
}

// NewRegisterProtocolDependencyRequestWithBody constructs an http.Request for the RegisterProtocolDependency method, with any body, and a specified content type
func NewRegisterProtocolDependencyRequestWithBody(server string, id openapi_types.UUID, versionId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "version_id", versionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/services/%s/versions/%s/dependencies", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPublishProtocolRequest calls the generic PublishProtocol builder with application/json body
func NewPublishProtocolRequest(server string, id openapi_types.UUID, versionId openapi_types.UUID, params *PublishProtocolParams, body PublishProtocolJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPublishProtocolRequestWithBody(server, id, versionId, params, "application/json", bodyReader)
}

// NewPublishProtocolRequestWithBody constructs an http.Request for the PublishProtocol method, with any body, and a specified content type
func NewPublishProtocolRequestWithBody(server string, id openapi_types.UUID, versionId openapi_types.UUID, params *PublishProtocolParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "version_id", versionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/services/%s/versions/%s/protocol", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Format != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "format", *params.Format, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Name != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "name", *params.Name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ListServicesWithResponse Список сервисов
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /services (the `ListServices` operationId).
	ListServicesWithResponse(ctx context.Context, params *ListServicesParams, reqEditors ...RequestEditorFn) (*ListServicesResponse, error)

	// GetServiceWithResponse Получить сервис по ID
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /services/{id} (the `GetService` operationId).
	GetServiceWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetServiceResponse, error)

	// GetProtocolWithResponse Получить протокол сервиса
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /services/{id}/protocol (the `GetProtocol` operationId).
	GetProtocolWithResponse(ctx context.Context, id openapi_types.UUID, params *GetProtocolParams, reqEditors ...RequestEditorFn) (*GetProtocolResponse, error)

	// CheckProtocolCompatibilityWithBodyWithResponse Проверить совместимость контракта-кандидата с потребителями
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /services/{id}/protocol/compatibility (the `CheckProtocolCompatibility` operationId).
	CheckProtocolCompatibilityWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, params *CheckProtocolCompatibilityParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CheckProtocolCompatibilityResponse, error)

	// CheckProtocolCompatibilityWithResponse Проверить совместимость контракта-кандидата с потребителями
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /services/{id}/protocol/compatibility (the `CheckProtocolCompatibility` operationId).
	CheckProtocolCompatibilityWithResponse(ctx context.Context, id openapi_types.UUID, params *CheckProtocolCompatibilityParams, body CheckProtocolCompatibilityJSONRequestBody, reqEditors ...RequestEditorFn) (*CheckProtocolCompatibilityResponse, error)

	// PublishVersionWithBodyWithResponse Опубликовать версию сервиса
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /services/{id}/versions (the `PublishVersion` operationId).
	PublishVersionWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublishVersionResponse, error)

	// PublishVersionWithResponse Опубликовать версию сервиса
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /services/{id}/versions (the `PublishVersion` operationId).
	PublishVersionWithResponse(ctx context.Context, id openapi_types.UUID, body PublishVersionJSONRequestBody, reqEditors ...RequestEditorFn) (*PublishVersionResponse, error)

	// RegisterProtocolDependencyWithBodyWithResponse Зарегистрировать зависимость версии от контракта другого сервиса
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /services/{id}/versions/{version_id}/dependencies (the `RegisterProtocolDependency` operationId).
	RegisterProtocolDependencyWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterProtocolDependencyResponse, error)

	// RegisterProtocolDependencyWithResponse Зарегистрировать зависимость версии от контракта другого сервиса
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /services/{id}/versions/{version_id}/dependencies (the `RegisterProtocolDependency` operationId).
	RegisterProtocolDependencyWithResponse(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, body RegisterProtocolDependencyJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterProtocolDependencyResponse, error)

	// PublishProtocolWithBodyWithResponse Опубликовать протокол версии сервиса
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /services/{id}/versions/{version_id}/protocol (the `PublishProtocol` operationId).
	PublishProtocolWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, params *PublishProtocolParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublishProtocolResponse, error)

	// PublishProtocolWithResponse Опубликовать протокол версии сервиса
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /services/{id}/versions/{version_id}/protocol (the `PublishProtocol` operationId).
	PublishProtocolWithResponse(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, params *PublishProtocolParams, body PublishProtocolJSONRequestBody, reqEditors ...RequestEditorFn) (*PublishProtocolResponse, error)
}

type ListServicesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]ServiceResponse
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *ErrorModel
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListServicesResponse) GetJSON200() *[]ServiceResponse {
	return r.JSON200
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r ListServicesResponse) GetApplicationproblemJSONDefault() *ErrorModel {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r ListServicesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListServicesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListServicesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListServicesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetServiceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ServiceResponse
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *ErrorModel
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetServiceResponse) GetJSON200() *ServiceResponse {
	return r.JSON200
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r GetServiceResponse) GetApplicationproblemJSONDefault() *ErrorModel {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r GetServiceResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetServiceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetServiceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetServiceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetProtocolResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ProtocolView
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *ErrorModel
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetProtocolResponse) GetJSON200() *ProtocolView {
	return r.JSON200
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r GetProtocolResponse) GetApplicationproblemJSONDefault() *ErrorModel {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r GetProtocolResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetProtocolResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProtocolResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetProtocolResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CheckProtocolCompatibilityResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *CompatibilityReportResponse
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *ErrorModel
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r CheckProtocolCompatibilityResponse) GetJSON200() *CompatibilityReportResponse {
	return r.JSON200
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r CheckProtocolCompatibilityResponse) GetApplicationproblemJSONDefault() *ErrorModel {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r CheckProtocolCompatibilityResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CheckProtocolCompatibilityResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CheckProtocolCompatibilityResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CheckProtocolCompatibilityResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PublishVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *VersionResponse
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *VersionResponse
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *ErrorModel
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PublishVersionResponse) GetJSON200() *VersionResponse {
	return r.JSON200
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r PublishVersionResponse) GetJSON201() *VersionResponse {
	return r.JSON201
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r PublishVersionResponse) GetApplicationproblemJSONDefault() *ErrorModel {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r PublishVersionResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PublishVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublishVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PublishVersionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RegisterProtocolDependencyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ProtocolDependencyResponse
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *ProtocolDependencyResponse
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *ErrorModel
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r RegisterProtocolDependencyResponse) GetJSON200() *ProtocolDependencyResponse {
	return r.JSON200
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r RegisterProtocolDependencyResponse) GetJSON201() *ProtocolDependencyResponse {
	return r.JSON201
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r RegisterProtocolDependencyResponse) GetApplicationproblemJSONDefault() *ErrorModel {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r RegisterProtocolDependencyResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r RegisterProtocolDependencyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RegisterProtocolDependencyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RegisterProtocolDependencyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PublishProtocolResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ProtocolPublishedResponse
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *ProtocolPublishedResponse
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *ErrorModel
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PublishProtocolResponse) GetJSON200() *ProtocolPublishedResponse {
	return r.JSON200
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r PublishProtocolResponse) GetJSON201() *ProtocolPublishedResponse {
	return r.JSON201
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r PublishProtocolResponse) GetApplicationproblemJSONDefault() *ErrorModel {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r PublishProtocolResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PublishProtocolResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublishProtocolResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PublishProtocolResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListServicesWithResponse Список сервисов
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /services (the `ListServices` operationId).
func (c *ClientWithResponses) ListServicesWithResponse(ctx context.Context, params *ListServicesParams, reqEditors ...RequestEditorFn) (*ListServicesResponse, error) {
	rsp, err := c.ListServices(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListServicesResponse(rsp)
}

// GetServiceWithResponse Получить сервис по ID
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /services/{id} (the `GetService` operationId).
func (c *ClientWithResponses) GetServiceWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetServiceResponse, error) {
	rsp, err := c.GetService(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetServiceResponse(rsp)
}

// GetProtocolWithResponse Получить протокол сервиса
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /services/{id}/protocol (the `GetProtocol` operationId).
func (c *ClientWithResponses) GetProtocolWithResponse(ctx context.Context, id openapi_types.UUID, params *GetProtocolParams, reqEditors ...RequestEditorFn) (*GetProtocolResponse, error) {
	rsp, err := c.GetProtocol(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProtocolResponse(rsp)
}

// CheckProtocolCompatibilityWithBodyWithResponse Проверить совместимость контракта-кандидата с потребителями
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /services/{id}/protocol/compatibility (the `CheckProtocolCompatibility` operationId).
func (c *ClientWithResponses) CheckProtocolCompatibilityWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, params *CheckProtocolCompatibilityParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CheckProtocolCompatibilityResponse, error) {
	rsp, err := c.CheckProtocolCompatibilityWithBody(ctx, id, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCheckProtocolCompatibilityResponse(rsp)
}

// CheckProtocolCompatibilityWithResponse Проверить совместимость контракта-кандидата с потребителями
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /services/{id}/protocol/compatibility (the `CheckProtocolCompatibility` operationId).
func (c *ClientWithResponses) CheckProtocolCompatibilityWithResponse(ctx context.Context, id openapi_types.UUID, params *CheckProtocolCompatibilityParams, body CheckProtocolCompatibilityJSONRequestBody, reqEditors ...RequestEditorFn) (*CheckProtocolCompatibilityResponse, error) {
	rsp, err := c.CheckProtocolCompatibility(ctx, id, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCheckProtocolCompatibilityResponse(rsp)
}

// PublishVersionWithBodyWithResponse Опубликовать версию сервиса
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /services/{id}/versions (the `PublishVersion` operationId).
func (c *ClientWithResponses) PublishVersionWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublishVersionResponse, error) {
	rsp, err := c.PublishVersionWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublishVersionResponse(rsp)
}

// PublishVersionWithResponse Опубликовать версию сервиса
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /services/{id}/versions (the `PublishVersion` operationId).
func (c *ClientWithResponses) PublishVersionWithResponse(ctx context.Context, id openapi_types.UUID, body PublishVersionJSONRequestBody, reqEditors ...RequestEditorFn) (*PublishVersionResponse, error) {
	rsp, err := c.PublishVersion(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublishVersionResponse(rsp)
}

// RegisterProtocolDependencyWithBodyWithResponse Зарегистрировать зависимость версии от контракта другого сервиса
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /services/{id}/versions/{version_id}/dependencies (the `RegisterProtocolDependency` operationId).
func (c *ClientWithResponses) RegisterProtocolDependencyWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterProtocolDependencyResponse, error) {
	rsp, err := c.RegisterProtocolDependencyWithBody(ctx, id, versionId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterProtocolDependencyResponse(rsp)
}

// RegisterProtocolDependencyWithResponse Зарегистрировать зависимость версии от контракта другого сервиса
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /services/{id}/versions/{version_id}/dependencies (the `RegisterProtocolDependency` operationId).
func (c *ClientWithResponses) RegisterProtocolDependencyWithResponse(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, body RegisterProtocolDependencyJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterProtocolDependencyResponse, error) {
	rsp, err := c.RegisterProtocolDependency(ctx, id, versionId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterProtocolDependencyResponse(rsp)
}

// PublishProtocolWithBodyWithResponse Опубликовать протокол версии сервиса
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /services/{id}/versions/{version_id}/protocol (the `PublishProtocol` operationId).
func (c *ClientWithResponses) PublishProtocolWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, params *PublishProtocolParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublishProtocolResponse, error) {
	rsp, err := c.PublishProtocolWithBody(ctx, id, versionId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublishProtocolResponse(rsp)
}

// PublishProtocolWithResponse Опубликовать протокол версии сервиса
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /services/{id}/versions/{version_id}/protocol (the `PublishProtocol` operationId).
func (c *ClientWithResponses) PublishProtocolWithResponse(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, params *PublishProtocolParams, body PublishProtocolJSONRequestBody, reqEditors ...RequestEditorFn) (*PublishProtocolResponse, error) {
	rsp, err := c.PublishProtocol(ctx, id, versionId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublishProtocolResponse(rsp)
}

// ParseListServicesResponse parses an HTTP response from a ListServicesWithResponse call
func ParseListServicesResponse(rsp *http.Response) (*ListServicesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListServicesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []ServiceResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetServiceResponse parses an HTTP response from a GetServiceWithResponse call
func ParseGetServiceResponse(rsp *http.Response) (*GetServiceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetServiceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ServiceResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetProtocolResponse parses an HTTP response from a GetProtocolWithResponse call
func ParseGetProtocolResponse(rsp *http.Response) (*GetProtocolResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProtocolResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProtocolView
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseCheckProtocolCompatibilityResponse parses an HTTP response from a CheckProtocolCompatibilityWithResponse call
func ParseCheckProtocolCompatibilityResponse(rsp *http.Response) (*CheckProtocolCompatibilityResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CheckProtocolCompatibilityResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CompatibilityReportResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePublishVersionResponse parses an HTTP response from a PublishVersionWithResponse call
func ParsePublishVersionResponse(rsp *http.Response) (*PublishVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublishVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VersionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest VersionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseRegisterProtocolDependencyResponse parses an HTTP response from a RegisterProtocolDependencyWithResponse call
func ParseRegisterProtocolDependencyResponse(rsp *http.Response) (*RegisterProtocolDependencyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RegisterProtocolDependencyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProtocolDependencyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ProtocolDependencyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePublishProtocolResponse parses an HTTP response from a PublishProtocolWithResponse call
func ParsePublishProtocolResponse(rsp *http.Response) (*PublishProtocolResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublishProtocolResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProtocolPublishedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ProtocolPublishedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}
