// Package platformapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package platformapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CompatibilityChangeResponse defines model for CompatibilityChangeResponse.
type CompatibilityChangeResponse struct {
	Breaking    bool    `json:"breaking"`
	Description string  `json:"description"`
	Kind        string  `json:"kind"`
	Operation   *string `json:"operation,omitempty"`
}

// CompatibilityReportResponse defines model for CompatibilityReportResponse.
type CompatibilityReportResponse struct {
	// Schema A URL to the JSON Schema for this object.
	Schema    *string                         `json:"$schema,omitempty"`
	Breaking  bool                            `json:"breaking"`
	Consumers []ConsumerCompatibilityResponse `json:"consumers"`
}

// ConsumerCompatibilityResponse defines model for ConsumerCompatibilityResponse.
type ConsumerCompatibilityResponse struct {
	Breaking              bool                          `json:"breaking"`
	Changes               []CompatibilityChangeResponse `json:"changes"`
	Comparable            bool                          `json:"comparable"`
	ConsumerServiceId     openapi_types.UUID            `json:"consumer_service_id"`
	ConsumerServiceName   string                        `json:"consumer_service_name"`
	ConsumerVersionId     openapi_types.UUID            `json:"consumer_version_id"`
	ConsumerVersionNumber int64                         `json:"consumer_version_number"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Location Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	Location *string `json:"location,omitempty"`

	// Message Error message text
	Message *string `json:"message,omitempty"`

	// Value The value at the given location
	Value interface{} `json:"value,omitempty"`
}

// ErrorModel defines model for ErrorModel.
type ErrorModel struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Errors Optional list of individual error details
	Errors *[]ErrorDetail `json:"errors,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int64 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	Title *string `json:"title,omitempty"`

	// Type A URI reference to human-readable documentation for the error.
	Type *string `json:"type,omitempty"`
}

// ProtocolDependencyResponse defines model for ProtocolDependencyResponse.
type ProtocolDependencyResponse struct {
	// Schema A URL to the JSON Schema for this object.
	Schema            *string            `json:"$schema,omitempty"`
	ConsumerServiceId openapi_types.UUID `json:"consumer_service_id"`
	ConsumerVersionId openapi_types.UUID `json:"consumer_version_id"`
	Format            string             `json:"format"`
	Id                openapi_types.UUID `json:"id"`
	ProducerServiceId openapi_types.UUID `json:"producer_service_id"`
	RegisteredAt      time.Time          `json:"registered_at"`
}

// ProtocolPublishedResponse defines model for ProtocolPublishedResponse.
type ProtocolPublishedResponse struct {
	// Schema A URL to the JSON Schema for this object.
	Schema    *string                         `json:"$schema,omitempty"`
	Breaking  bool                            `json:"breaking"`
	Consumers []ConsumerCompatibilityResponse `json:"consumers"`
	Protocol  *ProtocolResponse               `json:"protocol,omitempty"`
	Published bool                            `json:"published"`
}

// ProtocolResponse defines model for ProtocolResponse.
type ProtocolResponse struct {
	Format        string             `json:"format"`
	PublishedAt   time.Time          `json:"published_at"`
	ServiceId     openapi_types.UUID `json:"service_id"`
	VersionId     openapi_types.UUID `json:"version_id"`
	VersionNumber int64              `json:"version_number"`
}

// ProtocolView defines model for ProtocolView.
type ProtocolView struct {
	// Schema A URL to the JSON Schema for this object.
	Schema        *string                 `json:"$schema,omitempty"`
	Document      *map[string]interface{} `json:"document,omitempty"`
	Format        *string                 `json:"format,omitempty"`
	Published     bool                    `json:"published"`
	PublishedAt   *time.Time              `json:"published_at,omitempty"`
	ServiceId     openapi_types.UUID      `json:"service_id"`
	VersionId     *openapi_types.UUID     `json:"version_id,omitempty"`
	VersionNumber *int64                  `json:"version_number,omitempty"`
}

// PublishVersionInputBody defines model for PublishVersionInputBody.
type PublishVersionInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// CommitRevision Идентификатор коммита
	CommitRevision string `json:"commit_revision"`
}

// RegisterProtocolDependencyInputBody defines model for RegisterProtocolDependencyInputBody.
type RegisterProtocolDependencyInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Document Снимок контракта продьюсера, на котором собрана версия (OpenAPI-документ)
	Document map[string]interface{} `json:"document"`

	// ProducerServiceId ID сервиса, на контракте которого собрана версия
	ProducerServiceId openapi_types.UUID `json:"producer_service_id"`

	// SupersedePrevious Снять зависимости прочих версий этого потребителя от того же продьюсера, оставив только регистрируемую (по умолчанию нет)
	SupersedePrevious *bool `json:"supersede_previous,omitempty"`
}

// ServiceResponse defines model for ServiceResponse.
type ServiceResponse struct {
	// Schema A URL to the JSON Schema for this object.
	Schema    *string            `json:"$schema,omitempty"`
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
}

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// Schema A URL to the JSON Schema for this object.
	Schema         *string            `json:"$schema,omitempty"`
	CommitRevision string             `json:"commit_revision"`
	CreatedAt      time.Time          `json:"created_at"`
	Id             openapi_types.UUID `json:"id"`
	Number         int64              `json:"number"`
}

// ListServicesParams defines parameters for ListServices.
type ListServicesParams struct {
	// Name Фильтр по имени сервиса (точное совпадение); можно повторять — вернутся все совпавшие. Пусто — весь перечень
	Name *[]string `form:"name,omitempty" json:"name,omitempty"`
}

// CheckProtocolCompatibilityJSONBody defines parameters for CheckProtocolCompatibility.
type CheckProtocolCompatibilityJSONBody map[string]interface{}

// PublishProtocolJSONBody defines parameters for PublishProtocol.
type PublishProtocolJSONBody map[string]interface{}

// CheckProtocolCompatibilityJSONRequestBody defines body for CheckProtocolCompatibility for application/json ContentType.
type CheckProtocolCompatibilityJSONRequestBody CheckProtocolCompatibilityJSONBody

// PublishVersionJSONRequestBody defines body for PublishVersion for application/json ContentType.
type PublishVersionJSONRequestBody = PublishVersionInputBody

// RegisterProtocolDependencyJSONRequestBody defines body for RegisterProtocolDependency for application/json ContentType.
type RegisterProtocolDependencyJSONRequestBody = RegisterProtocolDependencyInputBody

// PublishProtocolJSONRequestBody defines body for PublishProtocol for application/json ContentType.
type PublishProtocolJSONRequestBody PublishProtocolJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListServices request
	ListServices(ctx context.Context, params *ListServicesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetService request
	GetService(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProtocol request
	GetProtocol(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CheckProtocolCompatibilityWithBody request with any body
	CheckProtocolCompatibilityWithBody(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CheckProtocolCompatibility(ctx context.Context, id openapi_types.UUID, body CheckProtocolCompatibilityJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PublishVersionWithBody request with any body
	PublishVersionWithBody(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PublishVersion(ctx context.Context, id openapi_types.UUID, body PublishVersionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RegisterProtocolDependencyWithBody request with any body
	RegisterProtocolDependencyWithBody(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RegisterProtocolDependency(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, body RegisterProtocolDependencyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PublishProtocolWithBody request with any body
	PublishProtocolWithBody(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PublishProtocol(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, body PublishProtocolJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListServices(ctx context.Context, params *ListServicesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListServicesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetService(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetServiceRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetProtocol(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProtocolRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CheckProtocolCompatibilityWithBody(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCheckProtocolCompatibilityRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CheckProtocolCompatibility(ctx context.Context, id openapi_types.UUID, body CheckProtocolCompatibilityJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCheckProtocolCompatibilityRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublishVersionWithBody(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublishVersionRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublishVersion(ctx context.Context, id openapi_types.UUID, body PublishVersionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublishVersionRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RegisterProtocolDependencyWithBody(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterProtocolDependencyRequestWithBody(c.Server, id, versionId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RegisterProtocolDependency(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, body RegisterProtocolDependencyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterProtocolDependencyRequest(c.Server, id, versionId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublishProtocolWithBody(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublishProtocolRequestWithBody(c.Server, id, versionId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublishProtocol(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, body PublishProtocolJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublishProtocolRequest(c.Server, id, versionId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListServicesRequest generates requests for ListServices
func NewListServicesRequest(server string, params *ListServicesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/services")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Name != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "name", *params.Name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetServiceRequest generates requests for GetService
func NewGetServiceRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/services/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetProtocolRequest generates requests for GetProtocol
func NewGetProtocolRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/services/%s/protocol", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCheckProtocolCompatibilityRequest calls the generic CheckProtocolCompatibility builder with application/json body
func NewCheckProtocolCompatibilityRequest(server string, id openapi_types.UUID, body CheckProtocolCompatibilityJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCheckProtocolCompatibilityRequestWithBody(server, id, "application/json", bodyReader)
}

// NewCheckProtocolCompatibilityRequestWithBody generates requests for CheckProtocolCompatibility with any type of body
func NewCheckProtocolCompatibilityRequestWithBody(server string, id openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/services/%s/protocol/compatibility", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPublishVersionRequest calls the generic PublishVersion builder with application/json body
func NewPublishVersionRequest(server string, id openapi_types.UUID, body PublishVersionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPublishVersionRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPublishVersionRequestWithBody generates requests for PublishVersion with any type of body
func NewPublishVersionRequestWithBody(server string, id openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/services/%s/versions", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRegisterProtocolDependencyRequest calls the generic RegisterProtocolDependency builder with application/json body
func NewRegisterProtocolDependencyRequest(server string, id openapi_types.UUID, versionId openapi_types.UUID, body RegisterProtocolDependencyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRegisterProtocolDependencyRequestWithBody(server, id, versionId, "application/json", bodyReader)
}

// NewRegisterProtocolDependencyRequestWithBody generates requests for RegisterProtocolDependency with any type of body
func NewRegisterProtocolDependencyRequestWithBody(server string, id openapi_types.UUID, versionId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "version_id", versionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/services/%s/versions/%s/dependencies", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPublishProtocolRequest calls the generic PublishProtocol builder with application/json body
func NewPublishProtocolRequest(server string, id openapi_types.UUID, versionId openapi_types.UUID, body PublishProtocolJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPublishProtocolRequestWithBody(server, id, versionId, "application/json", bodyReader)
}

// NewPublishProtocolRequestWithBody generates requests for PublishProtocol with any type of body
func NewPublishProtocolRequestWithBody(server string, id openapi_types.UUID, versionId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "version_id", versionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/services/%s/versions/%s/protocol", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListServicesWithResponse request
	ListServicesWithResponse(ctx context.Context, params *ListServicesParams, reqEditors ...RequestEditorFn) (*ListServicesResponse, error)

	// GetServiceWithResponse request
	GetServiceWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetServiceResponse, error)

	// GetProtocolWithResponse request
	GetProtocolWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetProtocolResponse, error)

	// CheckProtocolCompatibilityWithBodyWithResponse request with any body
	CheckProtocolCompatibilityWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CheckProtocolCompatibilityResponse, error)

	CheckProtocolCompatibilityWithResponse(ctx context.Context, id openapi_types.UUID, body CheckProtocolCompatibilityJSONRequestBody, reqEditors ...RequestEditorFn) (*CheckProtocolCompatibilityResponse, error)

	// PublishVersionWithBodyWithResponse request with any body
	PublishVersionWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublishVersionResponse, error)

	PublishVersionWithResponse(ctx context.Context, id openapi_types.UUID, body PublishVersionJSONRequestBody, reqEditors ...RequestEditorFn) (*PublishVersionResponse, error)

	// RegisterProtocolDependencyWithBodyWithResponse request with any body
	RegisterProtocolDependencyWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterProtocolDependencyResponse, error)

	RegisterProtocolDependencyWithResponse(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, body RegisterProtocolDependencyJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterProtocolDependencyResponse, error)

	// PublishProtocolWithBodyWithResponse request with any body
	PublishProtocolWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublishProtocolResponse, error)

	PublishProtocolWithResponse(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, body PublishProtocolJSONRequestBody, reqEditors ...RequestEditorFn) (*PublishProtocolResponse, error)
}

type ListServicesResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *[]ServiceResponse
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r ListServicesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListServicesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListServicesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetServiceResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *ServiceResponse
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r GetServiceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetServiceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetServiceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetProtocolResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *ProtocolView
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r GetProtocolResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProtocolResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetProtocolResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CheckProtocolCompatibilityResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *CompatibilityReportResponse
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r CheckProtocolCompatibilityResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CheckProtocolCompatibilityResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CheckProtocolCompatibilityResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PublishVersionResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON201                       *VersionResponse
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PublishVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublishVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PublishVersionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RegisterProtocolDependencyResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON201                       *ProtocolDependencyResponse
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r RegisterProtocolDependencyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RegisterProtocolDependencyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RegisterProtocolDependencyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PublishProtocolResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON201                       *ProtocolPublishedResponse
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PublishProtocolResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublishProtocolResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PublishProtocolResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListServicesWithResponse request returning *ListServicesResponse
func (c *ClientWithResponses) ListServicesWithResponse(ctx context.Context, params *ListServicesParams, reqEditors ...RequestEditorFn) (*ListServicesResponse, error) {
	rsp, err := c.ListServices(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListServicesResponse(rsp)
}

// GetServiceWithResponse request returning *GetServiceResponse
func (c *ClientWithResponses) GetServiceWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetServiceResponse, error) {
	rsp, err := c.GetService(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetServiceResponse(rsp)
}

// GetProtocolWithResponse request returning *GetProtocolResponse
func (c *ClientWithResponses) GetProtocolWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetProtocolResponse, error) {
	rsp, err := c.GetProtocol(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProtocolResponse(rsp)
}

// CheckProtocolCompatibilityWithBodyWithResponse request with arbitrary body returning *CheckProtocolCompatibilityResponse
func (c *ClientWithResponses) CheckProtocolCompatibilityWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CheckProtocolCompatibilityResponse, error) {
	rsp, err := c.CheckProtocolCompatibilityWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCheckProtocolCompatibilityResponse(rsp)
}

func (c *ClientWithResponses) CheckProtocolCompatibilityWithResponse(ctx context.Context, id openapi_types.UUID, body CheckProtocolCompatibilityJSONRequestBody, reqEditors ...RequestEditorFn) (*CheckProtocolCompatibilityResponse, error) {
	rsp, err := c.CheckProtocolCompatibility(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCheckProtocolCompatibilityResponse(rsp)
}

// PublishVersionWithBodyWithResponse request with arbitrary body returning *PublishVersionResponse
func (c *ClientWithResponses) PublishVersionWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublishVersionResponse, error) {
	rsp, err := c.PublishVersionWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublishVersionResponse(rsp)
}

func (c *ClientWithResponses) PublishVersionWithResponse(ctx context.Context, id openapi_types.UUID, body PublishVersionJSONRequestBody, reqEditors ...RequestEditorFn) (*PublishVersionResponse, error) {
	rsp, err := c.PublishVersion(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublishVersionResponse(rsp)
}

// RegisterProtocolDependencyWithBodyWithResponse request with arbitrary body returning *RegisterProtocolDependencyResponse
func (c *ClientWithResponses) RegisterProtocolDependencyWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterProtocolDependencyResponse, error) {
	rsp, err := c.RegisterProtocolDependencyWithBody(ctx, id, versionId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterProtocolDependencyResponse(rsp)
}

func (c *ClientWithResponses) RegisterProtocolDependencyWithResponse(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, body RegisterProtocolDependencyJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterProtocolDependencyResponse, error) {
	rsp, err := c.RegisterProtocolDependency(ctx, id, versionId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterProtocolDependencyResponse(rsp)
}

// PublishProtocolWithBodyWithResponse request with arbitrary body returning *PublishProtocolResponse
func (c *ClientWithResponses) PublishProtocolWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublishProtocolResponse, error) {
	rsp, err := c.PublishProtocolWithBody(ctx, id, versionId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublishProtocolResponse(rsp)
}

func (c *ClientWithResponses) PublishProtocolWithResponse(ctx context.Context, id openapi_types.UUID, versionId openapi_types.UUID, body PublishProtocolJSONRequestBody, reqEditors ...RequestEditorFn) (*PublishProtocolResponse, error) {
	rsp, err := c.PublishProtocol(ctx, id, versionId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublishProtocolResponse(rsp)
}

// ParseListServicesResponse parses an HTTP response from a ListServicesWithResponse call
func ParseListServicesResponse(rsp *http.Response) (*ListServicesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListServicesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []ServiceResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetServiceResponse parses an HTTP response from a GetServiceWithResponse call
func ParseGetServiceResponse(rsp *http.Response) (*GetServiceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetServiceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ServiceResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetProtocolResponse parses an HTTP response from a GetProtocolWithResponse call
func ParseGetProtocolResponse(rsp *http.Response) (*GetProtocolResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProtocolResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProtocolView
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseCheckProtocolCompatibilityResponse parses an HTTP response from a CheckProtocolCompatibilityWithResponse call
func ParseCheckProtocolCompatibilityResponse(rsp *http.Response) (*CheckProtocolCompatibilityResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CheckProtocolCompatibilityResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CompatibilityReportResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePublishVersionResponse parses an HTTP response from a PublishVersionWithResponse call
func ParsePublishVersionResponse(rsp *http.Response) (*PublishVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublishVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest VersionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseRegisterProtocolDependencyResponse parses an HTTP response from a RegisterProtocolDependencyWithResponse call
func ParseRegisterProtocolDependencyResponse(rsp *http.Response) (*RegisterProtocolDependencyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RegisterProtocolDependencyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ProtocolDependencyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePublishProtocolResponse parses an HTTP response from a PublishProtocolWithResponse call
func ParsePublishProtocolResponse(rsp *http.Response) (*PublishProtocolResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublishProtocolResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ProtocolPublishedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}
