// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TraumTech/paas-cli/internal/controllers/auth_logout_command_cli (interfaces: UserLogout)
//
// Generated by this command:
//
//	mockgen -destination=dependencies_mock_test.go -package=authlogoutcommandcli github.com/TraumTech/paas-cli/internal/controllers/auth_logout_command_cli UserLogout
//

// Package authlogoutcommandcli is a generated GoMock package.
package authlogoutcommandcli

import (
	context "context"
	reflect "reflect"

	usecases "github.com/TraumTech/paas-cli/internal/usecases"
	gomock "go.uber.org/mock/gomock"
)

// MockUserLogout is a mock of UserLogout interface.
type MockUserLogout struct {
	ctrl     *gomock.Controller
	recorder *MockUserLogoutMockRecorder
	isgomock struct{}
}

// MockUserLogoutMockRecorder is the mock recorder for MockUserLogout.
type MockUserLogoutMockRecorder struct {
	mock *MockUserLogout
}

// NewMockUserLogout creates a new mock instance.
func NewMockUserLogout(ctrl *gomock.Controller) *MockUserLogout {
	mock := &MockUserLogout{ctrl: ctrl}
	mock.recorder = &MockUserLogoutMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserLogout) EXPECT() *MockUserLogoutMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUserLogout) Execute(ctx context.Context) (*usecases.LogoutResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx)
	ret0, _ := ret[0].(*usecases.LogoutResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockUserLogoutMockRecorder) Execute(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUserLogout)(nil).Execute), ctx)
}
