// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TraumTech/paas-cli/internal/controllers/dependency_register_command_cli (interfaces: DependencyRegistrar)
//
// Generated by this command:
//
//	mockgen -destination=dependencies_mock_test.go -package=dependencyregistercommandcli github.com/TraumTech/paas-cli/internal/controllers/dependency_register_command_cli DependencyRegistrar
//

// Package dependencyregistercommandcli is a generated GoMock package.
package dependencyregistercommandcli

import (
	context "context"
	reflect "reflect"

	entities "github.com/TraumTech/paas-cli/internal/entities"
	usecases "github.com/TraumTech/paas-cli/internal/usecases"
	gomock "go.uber.org/mock/gomock"
)

// MockDependencyRegistrar is a mock of DependencyRegistrar interface.
type MockDependencyRegistrar struct {
	ctrl     *gomock.Controller
	recorder *MockDependencyRegistrarMockRecorder
	isgomock struct{}
}

// MockDependencyRegistrarMockRecorder is the mock recorder for MockDependencyRegistrar.
type MockDependencyRegistrarMockRecorder struct {
	mock *MockDependencyRegistrar
}

// NewMockDependencyRegistrar creates a new mock instance.
func NewMockDependencyRegistrar(ctrl *gomock.Controller) *MockDependencyRegistrar {
	mock := &MockDependencyRegistrar{ctrl: ctrl}
	mock.recorder = &MockDependencyRegistrarMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDependencyRegistrar) EXPECT() *MockDependencyRegistrarMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDependencyRegistrar) Execute(ctx context.Context, in usecases.RegisterDependencyInput) (*entities.Dependency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*entities.Dependency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockDependencyRegistrarMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDependencyRegistrar)(nil).Execute), ctx, in)
}
