// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TraumTech/paas-cli/internal/controllers/protocol_compatibility_command_cli (interfaces: CompatibilityChecker)
//
// Generated by this command:
//
//	mockgen -destination=dependencies_mock_test.go -package=protocolcompatibilitycommandcli github.com/TraumTech/paas-cli/internal/controllers/protocol_compatibility_command_cli CompatibilityChecker
//

// Package protocolcompatibilitycommandcli is a generated GoMock package.
package protocolcompatibilitycommandcli

import (
	context "context"
	reflect "reflect"

	entities "github.com/TraumTech/paas-cli/internal/entities"
	usecases "github.com/TraumTech/paas-cli/internal/usecases"
	gomock "go.uber.org/mock/gomock"
)

// MockCompatibilityChecker is a mock of CompatibilityChecker interface.
type MockCompatibilityChecker struct {
	ctrl     *gomock.Controller
	recorder *MockCompatibilityCheckerMockRecorder
	isgomock struct{}
}

// MockCompatibilityCheckerMockRecorder is the mock recorder for MockCompatibilityChecker.
type MockCompatibilityCheckerMockRecorder struct {
	mock *MockCompatibilityChecker
}

// NewMockCompatibilityChecker creates a new mock instance.
func NewMockCompatibilityChecker(ctrl *gomock.Controller) *MockCompatibilityChecker {
	mock := &MockCompatibilityChecker{ctrl: ctrl}
	mock.recorder = &MockCompatibilityCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompatibilityChecker) EXPECT() *MockCompatibilityCheckerMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCompatibilityChecker) Execute(ctx context.Context, in usecases.CheckCompatibilityInput) (*entities.CompatibilityReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*entities.CompatibilityReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCompatibilityCheckerMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCompatibilityChecker)(nil).Execute), ctx, in)
}
