// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TraumTech/paas-cli/internal/controllers/protocol_fetch_command_cli (interfaces: ProtocolFetcher)
//
// Generated by this command:
//
//	mockgen -destination=dependencies_mock_test.go -package=protocolfetchcommandcli github.com/TraumTech/paas-cli/internal/controllers/protocol_fetch_command_cli ProtocolFetcher
//

// Package protocolfetchcommandcli is a generated GoMock package.
package protocolfetchcommandcli

import (
	context "context"
	reflect "reflect"

	usecases "github.com/TraumTech/paas-cli/internal/usecases"
	gomock "go.uber.org/mock/gomock"
)

// MockProtocolFetcher is a mock of ProtocolFetcher interface.
type MockProtocolFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockProtocolFetcherMockRecorder
	isgomock struct{}
}

// MockProtocolFetcherMockRecorder is the mock recorder for MockProtocolFetcher.
type MockProtocolFetcherMockRecorder struct {
	mock *MockProtocolFetcher
}

// NewMockProtocolFetcher creates a new mock instance.
func NewMockProtocolFetcher(ctrl *gomock.Controller) *MockProtocolFetcher {
	mock := &MockProtocolFetcher{ctrl: ctrl}
	mock.recorder = &MockProtocolFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProtocolFetcher) EXPECT() *MockProtocolFetcherMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockProtocolFetcher) Execute(ctx context.Context, in usecases.FetchProtocolInput) (*usecases.FetchProtocolResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*usecases.FetchProtocolResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockProtocolFetcherMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockProtocolFetcher)(nil).Execute), ctx, in)
}
