// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TraumTech/paas-cli/internal/controllers/version_publish_command_cli (interfaces: VersionPublisher)
//
// Generated by this command:
//
//	mockgen -destination=dependencies_mock_test.go -package=versionpublishcommandcli github.com/TraumTech/paas-cli/internal/controllers/version_publish_command_cli VersionPublisher
//

// Package versionpublishcommandcli is a generated GoMock package.
package versionpublishcommandcli

import (
	context "context"
	reflect "reflect"

	entities "github.com/TraumTech/paas-cli/internal/entities"
	usecases "github.com/TraumTech/paas-cli/internal/usecases"
	gomock "go.uber.org/mock/gomock"
)

// MockVersionPublisher is a mock of VersionPublisher interface.
type MockVersionPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockVersionPublisherMockRecorder
	isgomock struct{}
}

// MockVersionPublisherMockRecorder is the mock recorder for MockVersionPublisher.
type MockVersionPublisherMockRecorder struct {
	mock *MockVersionPublisher
}

// NewMockVersionPublisher creates a new mock instance.
func NewMockVersionPublisher(ctrl *gomock.Controller) *MockVersionPublisher {
	mock := &MockVersionPublisher{ctrl: ctrl}
	mock.recorder = &MockVersionPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVersionPublisher) EXPECT() *MockVersionPublisherMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockVersionPublisher) Execute(ctx context.Context, in usecases.PublishVersionInput) (*entities.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*entities.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockVersionPublisherMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockVersionPublisher)(nil).Execute), ctx, in)
}
