// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TraumTech/paas-cli/internal/controllers/cluster_connect_command_cli (interfaces: ClusterConnector)
//
// Generated by this command:
//
//	mockgen -destination=dependencies_mock_test.go -package=clusterconnectcommandcli github.com/TraumTech/paas-cli/internal/controllers/cluster_connect_command_cli ClusterConnector
//

// Package clusterconnectcommandcli is a generated GoMock package.
package clusterconnectcommandcli

import (
	context "context"
	reflect "reflect"

	entities "github.com/TraumTech/paas-cli/internal/entities"
	usecases "github.com/TraumTech/paas-cli/internal/usecases"
	gomock "go.uber.org/mock/gomock"
)

// MockClusterConnector is a mock of ClusterConnector interface.
type MockClusterConnector struct {
	ctrl     *gomock.Controller
	recorder *MockClusterConnectorMockRecorder
	isgomock struct{}
}

// MockClusterConnectorMockRecorder is the mock recorder for MockClusterConnector.
type MockClusterConnectorMockRecorder struct {
	mock *MockClusterConnector
}

// NewMockClusterConnector creates a new mock instance.
func NewMockClusterConnector(ctrl *gomock.Controller) *MockClusterConnector {
	mock := &MockClusterConnector{ctrl: ctrl}
	mock.recorder = &MockClusterConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterConnector) EXPECT() *MockClusterConnectorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockClusterConnector) Execute(ctx context.Context, input usecases.ConnectClusterInput, confirm usecases.ConfirmFunc) (*entities.ConnectedCluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input, confirm)
	ret0, _ := ret[0].(*entities.ConnectedCluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockClusterConnectorMockRecorder) Execute(ctx, input, confirm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockClusterConnector)(nil).Execute), ctx, input, confirm)
}
