// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TraumTech/paas-cli/internal/usecases (interfaces: DatabaseOperatorSource,ClusterDirectory,OperatorInstaller)
//
// Generated by this command:
//
//	mockgen -destination=dependencies_operator_mock_test.go -package=usecases github.com/TraumTech/paas-cli/internal/usecases DatabaseOperatorSource,ClusterDirectory,OperatorInstaller
//

// Package usecases is a generated GoMock package.
package usecases

import (
	context "context"
	reflect "reflect"

	entities "github.com/TraumTech/paas-cli/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockDatabaseOperatorSource is a mock of DatabaseOperatorSource interface.
type MockDatabaseOperatorSource struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseOperatorSourceMockRecorder
	isgomock struct{}
}

// MockDatabaseOperatorSourceMockRecorder is the mock recorder for MockDatabaseOperatorSource.
type MockDatabaseOperatorSourceMockRecorder struct {
	mock *MockDatabaseOperatorSource
}

// NewMockDatabaseOperatorSource creates a new mock instance.
func NewMockDatabaseOperatorSource(ctrl *gomock.Controller) *MockDatabaseOperatorSource {
	mock := &MockDatabaseOperatorSource{ctrl: ctrl}
	mock.recorder = &MockDatabaseOperatorSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseOperatorSource) EXPECT() *MockDatabaseOperatorSourceMockRecorder {
	return m.recorder
}

// Operator mocks base method.
func (m *MockDatabaseOperatorSource) Operator(ctx context.Context, engine string) (*entities.DatabaseOperator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Operator", ctx, engine)
	ret0, _ := ret[0].(*entities.DatabaseOperator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Operator indicates an expected call of Operator.
func (mr *MockDatabaseOperatorSourceMockRecorder) Operator(ctx, engine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Operator", reflect.TypeOf((*MockDatabaseOperatorSource)(nil).Operator), ctx, engine)
}

// MockClusterDirectory is a mock of ClusterDirectory interface.
type MockClusterDirectory struct {
	ctrl     *gomock.Controller
	recorder *MockClusterDirectoryMockRecorder
	isgomock struct{}
}

// MockClusterDirectoryMockRecorder is the mock recorder for MockClusterDirectory.
type MockClusterDirectoryMockRecorder struct {
	mock *MockClusterDirectory
}

// NewMockClusterDirectory creates a new mock instance.
func NewMockClusterDirectory(ctrl *gomock.Controller) *MockClusterDirectory {
	mock := &MockClusterDirectory{ctrl: ctrl}
	mock.recorder = &MockClusterDirectoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterDirectory) EXPECT() *MockClusterDirectoryMockRecorder {
	return m.recorder
}

// ListClusters mocks base method.
func (m *MockClusterDirectory) ListClusters(ctx context.Context) ([]entities.ConnectedCluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClusters", ctx)
	ret0, _ := ret[0].([]entities.ConnectedCluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClusters indicates an expected call of ListClusters.
func (mr *MockClusterDirectoryMockRecorder) ListClusters(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClusters", reflect.TypeOf((*MockClusterDirectory)(nil).ListClusters), ctx)
}

// MockOperatorInstaller is a mock of OperatorInstaller interface.
type MockOperatorInstaller struct {
	ctrl     *gomock.Controller
	recorder *MockOperatorInstallerMockRecorder
	isgomock struct{}
}

// MockOperatorInstallerMockRecorder is the mock recorder for MockOperatorInstaller.
type MockOperatorInstallerMockRecorder struct {
	mock *MockOperatorInstaller
}

// NewMockOperatorInstaller creates a new mock instance.
func NewMockOperatorInstaller(ctrl *gomock.Controller) *MockOperatorInstaller {
	mock := &MockOperatorInstaller{ctrl: ctrl}
	mock.recorder = &MockOperatorInstallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperatorInstaller) EXPECT() *MockOperatorInstallerMockRecorder {
	return m.recorder
}

// AccountName mocks base method.
func (m *MockOperatorInstaller) AccountName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountName")
	ret0, _ := ret[0].(string)
	return ret0
}

// AccountName indicates an expected call of AccountName.
func (mr *MockOperatorInstallerMockRecorder) AccountName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountName", reflect.TypeOf((*MockOperatorInstaller)(nil).AccountName))
}

// Install mocks base method.
func (m *MockOperatorInstaller) Install(ctx context.Context, kubeconfig, contextName string, op *entities.DatabaseOperator) (*entities.OperatorInstallReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Install", ctx, kubeconfig, contextName, op)
	ret0, _ := ret[0].(*entities.OperatorInstallReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Install indicates an expected call of Install.
func (mr *MockOperatorInstallerMockRecorder) Install(ctx, kubeconfig, contextName, op any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Install", reflect.TypeOf((*MockOperatorInstaller)(nil).Install), ctx, kubeconfig, contextName, op)
}

// Objects mocks base method.
func (m *MockOperatorInstaller) Objects(manifest string) ([]entities.ManifestObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Objects", manifest)
	ret0, _ := ret[0].([]entities.ManifestObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Objects indicates an expected call of Objects.
func (mr *MockOperatorInstallerMockRecorder) Objects(manifest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Objects", reflect.TypeOf((*MockOperatorInstaller)(nil).Objects), manifest)
}

// Target mocks base method.
func (m *MockOperatorInstaller) Target(kubeconfig, contextName string) (*ClusterTarget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Target", kubeconfig, contextName)
	ret0, _ := ret[0].(*ClusterTarget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Target indicates an expected call of Target.
func (mr *MockOperatorInstallerMockRecorder) Target(kubeconfig, contextName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Target", reflect.TypeOf((*MockOperatorInstaller)(nil).Target), kubeconfig, contextName)
}
