// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TraumTech/paas-cli/internal/usecases (interfaces: ProtocolSource,ProtocolStore,CandidateReader,CompatibilitySource,VersionPublisher,ProtocolPublisher,DependencyRegistrar,ManifestReader,ServiceResolver)
//
// Generated by this command:
//
//	mockgen -destination=dependencies_mock_test.go -package=usecases github.com/TraumTech/paas-cli/internal/usecases ProtocolSource,ProtocolStore,CandidateReader,CompatibilitySource,VersionPublisher,ProtocolPublisher,DependencyRegistrar,ManifestReader,ServiceResolver
//

// Package usecases is a generated GoMock package.
package usecases

import (
	context "context"
	reflect "reflect"

	entities "github.com/TraumTech/paas-cli/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockProtocolSource is a mock of ProtocolSource interface.
type MockProtocolSource struct {
	ctrl     *gomock.Controller
	recorder *MockProtocolSourceMockRecorder
	isgomock struct{}
}

// MockProtocolSourceMockRecorder is the mock recorder for MockProtocolSource.
type MockProtocolSourceMockRecorder struct {
	mock *MockProtocolSource
}

// NewMockProtocolSource creates a new mock instance.
func NewMockProtocolSource(ctrl *gomock.Controller) *MockProtocolSource {
	mock := &MockProtocolSource{ctrl: ctrl}
	mock.recorder = &MockProtocolSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProtocolSource) EXPECT() *MockProtocolSourceMockRecorder {
	return m.recorder
}

// FetchProtocol mocks base method.
func (m *MockProtocolSource) FetchProtocol(ctx context.Context, serviceID string) (*entities.Protocol, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchProtocol", ctx, serviceID)
	ret0, _ := ret[0].(*entities.Protocol)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchProtocol indicates an expected call of FetchProtocol.
func (mr *MockProtocolSourceMockRecorder) FetchProtocol(ctx, serviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchProtocol", reflect.TypeOf((*MockProtocolSource)(nil).FetchProtocol), ctx, serviceID)
}

// MockProtocolStore is a mock of ProtocolStore interface.
type MockProtocolStore struct {
	ctrl     *gomock.Controller
	recorder *MockProtocolStoreMockRecorder
	isgomock struct{}
}

// MockProtocolStoreMockRecorder is the mock recorder for MockProtocolStore.
type MockProtocolStoreMockRecorder struct {
	mock *MockProtocolStore
}

// NewMockProtocolStore creates a new mock instance.
func NewMockProtocolStore(ctrl *gomock.Controller) *MockProtocolStore {
	mock := &MockProtocolStore{ctrl: ctrl}
	mock.recorder = &MockProtocolStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProtocolStore) EXPECT() *MockProtocolStoreMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockProtocolStore) Save(ctx context.Context, protocol *entities.Protocol, destDir string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, protocol, destDir)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockProtocolStoreMockRecorder) Save(ctx, protocol, destDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockProtocolStore)(nil).Save), ctx, protocol, destDir)
}

// MockCandidateReader is a mock of CandidateReader interface.
type MockCandidateReader struct {
	ctrl     *gomock.Controller
	recorder *MockCandidateReaderMockRecorder
	isgomock struct{}
}

// MockCandidateReaderMockRecorder is the mock recorder for MockCandidateReader.
type MockCandidateReaderMockRecorder struct {
	mock *MockCandidateReader
}

// NewMockCandidateReader creates a new mock instance.
func NewMockCandidateReader(ctrl *gomock.Controller) *MockCandidateReader {
	mock := &MockCandidateReader{ctrl: ctrl}
	mock.recorder = &MockCandidateReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCandidateReader) EXPECT() *MockCandidateReaderMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockCandidateReader) Read(ctx context.Context, path string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ctx, path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockCandidateReaderMockRecorder) Read(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockCandidateReader)(nil).Read), ctx, path)
}

// MockCompatibilitySource is a mock of CompatibilitySource interface.
type MockCompatibilitySource struct {
	ctrl     *gomock.Controller
	recorder *MockCompatibilitySourceMockRecorder
	isgomock struct{}
}

// MockCompatibilitySourceMockRecorder is the mock recorder for MockCompatibilitySource.
type MockCompatibilitySourceMockRecorder struct {
	mock *MockCompatibilitySource
}

// NewMockCompatibilitySource creates a new mock instance.
func NewMockCompatibilitySource(ctrl *gomock.Controller) *MockCompatibilitySource {
	mock := &MockCompatibilitySource{ctrl: ctrl}
	mock.recorder = &MockCompatibilitySourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompatibilitySource) EXPECT() *MockCompatibilitySourceMockRecorder {
	return m.recorder
}

// CheckCompatibility mocks base method.
func (m *MockCompatibilitySource) CheckCompatibility(ctx context.Context, serviceID string, document []byte) (*entities.CompatibilityReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCompatibility", ctx, serviceID, document)
	ret0, _ := ret[0].(*entities.CompatibilityReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckCompatibility indicates an expected call of CheckCompatibility.
func (mr *MockCompatibilitySourceMockRecorder) CheckCompatibility(ctx, serviceID, document any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCompatibility", reflect.TypeOf((*MockCompatibilitySource)(nil).CheckCompatibility), ctx, serviceID, document)
}

// MockVersionPublisher is a mock of VersionPublisher interface.
type MockVersionPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockVersionPublisherMockRecorder
	isgomock struct{}
}

// MockVersionPublisherMockRecorder is the mock recorder for MockVersionPublisher.
type MockVersionPublisherMockRecorder struct {
	mock *MockVersionPublisher
}

// NewMockVersionPublisher creates a new mock instance.
func NewMockVersionPublisher(ctrl *gomock.Controller) *MockVersionPublisher {
	mock := &MockVersionPublisher{ctrl: ctrl}
	mock.recorder = &MockVersionPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVersionPublisher) EXPECT() *MockVersionPublisherMockRecorder {
	return m.recorder
}

// PublishVersion mocks base method.
func (m *MockVersionPublisher) PublishVersion(ctx context.Context, serviceID, commitRevision string) (*entities.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishVersion", ctx, serviceID, commitRevision)
	ret0, _ := ret[0].(*entities.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishVersion indicates an expected call of PublishVersion.
func (mr *MockVersionPublisherMockRecorder) PublishVersion(ctx, serviceID, commitRevision any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishVersion", reflect.TypeOf((*MockVersionPublisher)(nil).PublishVersion), ctx, serviceID, commitRevision)
}

// MockProtocolPublisher is a mock of ProtocolPublisher interface.
type MockProtocolPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockProtocolPublisherMockRecorder
	isgomock struct{}
}

// MockProtocolPublisherMockRecorder is the mock recorder for MockProtocolPublisher.
type MockProtocolPublisherMockRecorder struct {
	mock *MockProtocolPublisher
}

// NewMockProtocolPublisher creates a new mock instance.
func NewMockProtocolPublisher(ctrl *gomock.Controller) *MockProtocolPublisher {
	mock := &MockProtocolPublisher{ctrl: ctrl}
	mock.recorder = &MockProtocolPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProtocolPublisher) EXPECT() *MockProtocolPublisherMockRecorder {
	return m.recorder
}

// PublishProtocol mocks base method.
func (m *MockProtocolPublisher) PublishProtocol(ctx context.Context, serviceID, versionID string, document []byte) (*entities.ProtocolPublication, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishProtocol", ctx, serviceID, versionID, document)
	ret0, _ := ret[0].(*entities.ProtocolPublication)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishProtocol indicates an expected call of PublishProtocol.
func (mr *MockProtocolPublisherMockRecorder) PublishProtocol(ctx, serviceID, versionID, document any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishProtocol", reflect.TypeOf((*MockProtocolPublisher)(nil).PublishProtocol), ctx, serviceID, versionID, document)
}

// MockDependencyRegistrar is a mock of DependencyRegistrar interface.
type MockDependencyRegistrar struct {
	ctrl     *gomock.Controller
	recorder *MockDependencyRegistrarMockRecorder
	isgomock struct{}
}

// MockDependencyRegistrarMockRecorder is the mock recorder for MockDependencyRegistrar.
type MockDependencyRegistrarMockRecorder struct {
	mock *MockDependencyRegistrar
}

// NewMockDependencyRegistrar creates a new mock instance.
func NewMockDependencyRegistrar(ctrl *gomock.Controller) *MockDependencyRegistrar {
	mock := &MockDependencyRegistrar{ctrl: ctrl}
	mock.recorder = &MockDependencyRegistrarMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDependencyRegistrar) EXPECT() *MockDependencyRegistrarMockRecorder {
	return m.recorder
}

// RegisterDependency mocks base method.
func (m *MockDependencyRegistrar) RegisterDependency(ctx context.Context, serviceID, versionID, producerServiceID string, document []byte, methods []string, supersedePrevious bool) (*entities.Dependency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterDependency", ctx, serviceID, versionID, producerServiceID, document, methods, supersedePrevious)
	ret0, _ := ret[0].(*entities.Dependency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterDependency indicates an expected call of RegisterDependency.
func (mr *MockDependencyRegistrarMockRecorder) RegisterDependency(ctx, serviceID, versionID, producerServiceID, document, methods, supersedePrevious any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterDependency", reflect.TypeOf((*MockDependencyRegistrar)(nil).RegisterDependency), ctx, serviceID, versionID, producerServiceID, document, methods, supersedePrevious)
}

// MockManifestReader is a mock of ManifestReader interface.
type MockManifestReader struct {
	ctrl     *gomock.Controller
	recorder *MockManifestReaderMockRecorder
	isgomock struct{}
}

// MockManifestReaderMockRecorder is the mock recorder for MockManifestReader.
type MockManifestReaderMockRecorder struct {
	mock *MockManifestReader
}

// NewMockManifestReader creates a new mock instance.
func NewMockManifestReader(ctrl *gomock.Controller) *MockManifestReader {
	mock := &MockManifestReader{ctrl: ctrl}
	mock.recorder = &MockManifestReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManifestReader) EXPECT() *MockManifestReaderMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockManifestReader) Read(ctx context.Context, path string) (*entities.Manifest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ctx, path)
	ret0, _ := ret[0].(*entities.Manifest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockManifestReaderMockRecorder) Read(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockManifestReader)(nil).Read), ctx, path)
}

// MockServiceResolver is a mock of ServiceResolver interface.
type MockServiceResolver struct {
	ctrl     *gomock.Controller
	recorder *MockServiceResolverMockRecorder
	isgomock struct{}
}

// MockServiceResolverMockRecorder is the mock recorder for MockServiceResolver.
type MockServiceResolverMockRecorder struct {
	mock *MockServiceResolver
}

// NewMockServiceResolver creates a new mock instance.
func NewMockServiceResolver(ctrl *gomock.Controller) *MockServiceResolver {
	mock := &MockServiceResolver{ctrl: ctrl}
	mock.recorder = &MockServiceResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceResolver) EXPECT() *MockServiceResolverMockRecorder {
	return m.recorder
}

// ResolveIDs mocks base method.
func (m *MockServiceResolver) ResolveIDs(ctx context.Context, names []string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveIDs", ctx, names)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveIDs indicates an expected call of ResolveIDs.
func (mr *MockServiceResolverMockRecorder) ResolveIDs(ctx, names any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveIDs", reflect.TypeOf((*MockServiceResolver)(nil).ResolveIDs), ctx, names)
}
