// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TraumTech/paas-cli/internal/usecases (interfaces: ClusterAccessSource,ClusterProvisioner,ClusterRegistrar)
//
// Generated by this command:
//
//	mockgen -destination=dependencies_cluster_mock_test.go -package=usecases github.com/TraumTech/paas-cli/internal/usecases ClusterAccessSource,ClusterProvisioner,ClusterRegistrar
//

// Package usecases is a generated GoMock package.
package usecases

import (
	context "context"
	reflect "reflect"

	entities "github.com/TraumTech/paas-cli/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockClusterAccessSource is a mock of ClusterAccessSource interface.
type MockClusterAccessSource struct {
	ctrl     *gomock.Controller
	recorder *MockClusterAccessSourceMockRecorder
	isgomock struct{}
}

// MockClusterAccessSourceMockRecorder is the mock recorder for MockClusterAccessSource.
type MockClusterAccessSourceMockRecorder struct {
	mock *MockClusterAccessSource
}

// NewMockClusterAccessSource creates a new mock instance.
func NewMockClusterAccessSource(ctrl *gomock.Controller) *MockClusterAccessSource {
	mock := &MockClusterAccessSource{ctrl: ctrl}
	mock.recorder = &MockClusterAccessSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterAccessSource) EXPECT() *MockClusterAccessSourceMockRecorder {
	return m.recorder
}

// RequiredAccess mocks base method.
func (m *MockClusterAccessSource) RequiredAccess(ctx context.Context) ([]entities.AccessRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequiredAccess", ctx)
	ret0, _ := ret[0].([]entities.AccessRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequiredAccess indicates an expected call of RequiredAccess.
func (mr *MockClusterAccessSourceMockRecorder) RequiredAccess(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequiredAccess", reflect.TypeOf((*MockClusterAccessSource)(nil).RequiredAccess), ctx)
}

// MockClusterProvisioner is a mock of ClusterProvisioner interface.
type MockClusterProvisioner struct {
	ctrl     *gomock.Controller
	recorder *MockClusterProvisionerMockRecorder
	isgomock struct{}
}

// MockClusterProvisionerMockRecorder is the mock recorder for MockClusterProvisioner.
type MockClusterProvisionerMockRecorder struct {
	mock *MockClusterProvisioner
}

// NewMockClusterProvisioner creates a new mock instance.
func NewMockClusterProvisioner(ctrl *gomock.Controller) *MockClusterProvisioner {
	mock := &MockClusterProvisioner{ctrl: ctrl}
	mock.recorder = &MockClusterProvisionerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterProvisioner) EXPECT() *MockClusterProvisionerMockRecorder {
	return m.recorder
}

// AccountName mocks base method.
func (m *MockClusterProvisioner) AccountName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountName")
	ret0, _ := ret[0].(string)
	return ret0
}

// AccountName indicates an expected call of AccountName.
func (mr *MockClusterProvisionerMockRecorder) AccountName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountName", reflect.TypeOf((*MockClusterProvisioner)(nil).AccountName))
}

// Provision mocks base method.
func (m *MockClusterProvisioner) Provision(ctx context.Context, kubeconfig, contextName string, rules []entities.AccessRule) (*entities.ClusterCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Provision", ctx, kubeconfig, contextName, rules)
	ret0, _ := ret[0].(*entities.ClusterCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Provision indicates an expected call of Provision.
func (mr *MockClusterProvisionerMockRecorder) Provision(ctx, kubeconfig, contextName, rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Provision", reflect.TypeOf((*MockClusterProvisioner)(nil).Provision), ctx, kubeconfig, contextName, rules)
}

// Target mocks base method.
func (m *MockClusterProvisioner) Target(kubeconfig, contextName string) (*ClusterTarget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Target", kubeconfig, contextName)
	ret0, _ := ret[0].(*ClusterTarget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Target indicates an expected call of Target.
func (mr *MockClusterProvisionerMockRecorder) Target(kubeconfig, contextName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Target", reflect.TypeOf((*MockClusterProvisioner)(nil).Target), kubeconfig, contextName)
}

// MockClusterRegistrar is a mock of ClusterRegistrar interface.
type MockClusterRegistrar struct {
	ctrl     *gomock.Controller
	recorder *MockClusterRegistrarMockRecorder
	isgomock struct{}
}

// MockClusterRegistrarMockRecorder is the mock recorder for MockClusterRegistrar.
type MockClusterRegistrarMockRecorder struct {
	mock *MockClusterRegistrar
}

// NewMockClusterRegistrar creates a new mock instance.
func NewMockClusterRegistrar(ctrl *gomock.Controller) *MockClusterRegistrar {
	mock := &MockClusterRegistrar{ctrl: ctrl}
	mock.recorder = &MockClusterRegistrarMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterRegistrar) EXPECT() *MockClusterRegistrarMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockClusterRegistrar) Register(ctx context.Context, name string, credential entities.ClusterCredential) (*entities.ConnectedCluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, name, credential)
	ret0, _ := ret[0].(*entities.ConnectedCluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockClusterRegistrarMockRecorder) Register(ctx, name, credential any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockClusterRegistrar)(nil).Register), ctx, name, credential)
}
