// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TraumTech/paas-cli/internal/usecases (interfaces: ProtocolSource,ProtocolStore)
//
// Generated by this command:
//
//	mockgen -destination=dependencies_mock_test.go -package=usecases github.com/TraumTech/paas-cli/internal/usecases ProtocolSource,ProtocolStore
//

// Package usecases is a generated GoMock package.
package usecases

import (
	context "context"
	reflect "reflect"

	entities "github.com/TraumTech/paas-cli/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockProtocolSource is a mock of ProtocolSource interface.
type MockProtocolSource struct {
	ctrl     *gomock.Controller
	recorder *MockProtocolSourceMockRecorder
	isgomock struct{}
}

// MockProtocolSourceMockRecorder is the mock recorder for MockProtocolSource.
type MockProtocolSourceMockRecorder struct {
	mock *MockProtocolSource
}

// NewMockProtocolSource creates a new mock instance.
func NewMockProtocolSource(ctrl *gomock.Controller) *MockProtocolSource {
	mock := &MockProtocolSource{ctrl: ctrl}
	mock.recorder = &MockProtocolSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProtocolSource) EXPECT() *MockProtocolSourceMockRecorder {
	return m.recorder
}

// FetchProtocol mocks base method.
func (m *MockProtocolSource) FetchProtocol(ctx context.Context, serviceID string) (*entities.Protocol, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchProtocol", ctx, serviceID)
	ret0, _ := ret[0].(*entities.Protocol)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchProtocol indicates an expected call of FetchProtocol.
func (mr *MockProtocolSourceMockRecorder) FetchProtocol(ctx, serviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchProtocol", reflect.TypeOf((*MockProtocolSource)(nil).FetchProtocol), ctx, serviceID)
}

// MockProtocolStore is a mock of ProtocolStore interface.
type MockProtocolStore struct {
	ctrl     *gomock.Controller
	recorder *MockProtocolStoreMockRecorder
	isgomock struct{}
}

// MockProtocolStoreMockRecorder is the mock recorder for MockProtocolStore.
type MockProtocolStoreMockRecorder struct {
	mock *MockProtocolStore
}

// NewMockProtocolStore creates a new mock instance.
func NewMockProtocolStore(ctrl *gomock.Controller) *MockProtocolStore {
	mock := &MockProtocolStore{ctrl: ctrl}
	mock.recorder = &MockProtocolStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProtocolStore) EXPECT() *MockProtocolStoreMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockProtocolStore) Save(ctx context.Context, protocol *entities.Protocol, destDir string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, protocol, destDir)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockProtocolStoreMockRecorder) Save(ctx, protocol, destDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockProtocolStore)(nil).Save), ctx, protocol, destDir)
}
