// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TraumTech/paas-cli/internal/usecases (interfaces: ProtocolSource,ProtocolStore,CandidateReader,CompatibilitySource,VersionPublisher,BuildPublisher,ProtocolPublisher,DependencyRegistrar,ManifestReader,FormReader,ServiceResolver,CredentialAuthenticator,SessionInspector,SessionRevoker,SessionStore,BrowserAuthorizer,PersonalTokenDirectory)
//
// Generated by this command:
//
//	mockgen -destination=dependencies_mock_test.go -package=usecases github.com/TraumTech/paas-cli/internal/usecases ProtocolSource,ProtocolStore,CandidateReader,CompatibilitySource,VersionPublisher,BuildPublisher,ProtocolPublisher,DependencyRegistrar,ManifestReader,FormReader,ServiceResolver,CredentialAuthenticator,SessionInspector,SessionRevoker,SessionStore,BrowserAuthorizer,PersonalTokenDirectory
//

// Package usecases is a generated GoMock package.
package usecases

import (
	context "context"
	reflect "reflect"

	entities "github.com/TraumTech/paas-cli/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockProtocolSource is a mock of ProtocolSource interface.
type MockProtocolSource struct {
	ctrl     *gomock.Controller
	recorder *MockProtocolSourceMockRecorder
	isgomock struct{}
}

// MockProtocolSourceMockRecorder is the mock recorder for MockProtocolSource.
type MockProtocolSourceMockRecorder struct {
	mock *MockProtocolSource
}

// NewMockProtocolSource creates a new mock instance.
func NewMockProtocolSource(ctrl *gomock.Controller) *MockProtocolSource {
	mock := &MockProtocolSource{ctrl: ctrl}
	mock.recorder = &MockProtocolSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProtocolSource) EXPECT() *MockProtocolSourceMockRecorder {
	return m.recorder
}

// FetchProtocol mocks base method.
func (m *MockProtocolSource) FetchProtocol(ctx context.Context, serviceID string, methods []string) (*entities.Protocol, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchProtocol", ctx, serviceID, methods)
	ret0, _ := ret[0].(*entities.Protocol)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FetchProtocol indicates an expected call of FetchProtocol.
func (mr *MockProtocolSourceMockRecorder) FetchProtocol(ctx, serviceID, methods any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchProtocol", reflect.TypeOf((*MockProtocolSource)(nil).FetchProtocol), ctx, serviceID, methods)
}

// MockProtocolStore is a mock of ProtocolStore interface.
type MockProtocolStore struct {
	ctrl     *gomock.Controller
	recorder *MockProtocolStoreMockRecorder
	isgomock struct{}
}

// MockProtocolStoreMockRecorder is the mock recorder for MockProtocolStore.
type MockProtocolStoreMockRecorder struct {
	mock *MockProtocolStore
}

// NewMockProtocolStore creates a new mock instance.
func NewMockProtocolStore(ctrl *gomock.Controller) *MockProtocolStore {
	mock := &MockProtocolStore{ctrl: ctrl}
	mock.recorder = &MockProtocolStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProtocolStore) EXPECT() *MockProtocolStoreMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockProtocolStore) Save(ctx context.Context, protocol *entities.Protocol, destDir string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, protocol, destDir)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockProtocolStoreMockRecorder) Save(ctx, protocol, destDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockProtocolStore)(nil).Save), ctx, protocol, destDir)
}

// MockCandidateReader is a mock of CandidateReader interface.
type MockCandidateReader struct {
	ctrl     *gomock.Controller
	recorder *MockCandidateReaderMockRecorder
	isgomock struct{}
}

// MockCandidateReaderMockRecorder is the mock recorder for MockCandidateReader.
type MockCandidateReaderMockRecorder struct {
	mock *MockCandidateReader
}

// NewMockCandidateReader creates a new mock instance.
func NewMockCandidateReader(ctrl *gomock.Controller) *MockCandidateReader {
	mock := &MockCandidateReader{ctrl: ctrl}
	mock.recorder = &MockCandidateReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCandidateReader) EXPECT() *MockCandidateReaderMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockCandidateReader) Read(ctx context.Context, path string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ctx, path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockCandidateReaderMockRecorder) Read(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockCandidateReader)(nil).Read), ctx, path)
}

// MockCompatibilitySource is a mock of CompatibilitySource interface.
type MockCompatibilitySource struct {
	ctrl     *gomock.Controller
	recorder *MockCompatibilitySourceMockRecorder
	isgomock struct{}
}

// MockCompatibilitySourceMockRecorder is the mock recorder for MockCompatibilitySource.
type MockCompatibilitySourceMockRecorder struct {
	mock *MockCompatibilitySource
}

// NewMockCompatibilitySource creates a new mock instance.
func NewMockCompatibilitySource(ctrl *gomock.Controller) *MockCompatibilitySource {
	mock := &MockCompatibilitySource{ctrl: ctrl}
	mock.recorder = &MockCompatibilitySourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompatibilitySource) EXPECT() *MockCompatibilitySourceMockRecorder {
	return m.recorder
}

// CheckCompatibility mocks base method.
func (m *MockCompatibilitySource) CheckCompatibility(ctx context.Context, serviceID string, format entities.ProtocolFormat, document []byte) (*entities.CompatibilityReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCompatibility", ctx, serviceID, format, document)
	ret0, _ := ret[0].(*entities.CompatibilityReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckCompatibility indicates an expected call of CheckCompatibility.
func (mr *MockCompatibilitySourceMockRecorder) CheckCompatibility(ctx, serviceID, format, document any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCompatibility", reflect.TypeOf((*MockCompatibilitySource)(nil).CheckCompatibility), ctx, serviceID, format, document)
}

// MockVersionPublisher is a mock of VersionPublisher interface.
type MockVersionPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockVersionPublisherMockRecorder
	isgomock struct{}
}

// MockVersionPublisherMockRecorder is the mock recorder for MockVersionPublisher.
type MockVersionPublisherMockRecorder struct {
	mock *MockVersionPublisher
}

// NewMockVersionPublisher creates a new mock instance.
func NewMockVersionPublisher(ctrl *gomock.Controller) *MockVersionPublisher {
	mock := &MockVersionPublisher{ctrl: ctrl}
	mock.recorder = &MockVersionPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVersionPublisher) EXPECT() *MockVersionPublisherMockRecorder {
	return m.recorder
}

// PublishVersion mocks base method.
func (m *MockVersionPublisher) PublishVersion(ctx context.Context, serviceID, environment, commitRevision, branch, image string, form *entities.VersionForm) (*entities.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishVersion", ctx, serviceID, environment, commitRevision, branch, image, form)
	ret0, _ := ret[0].(*entities.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishVersion indicates an expected call of PublishVersion.
func (mr *MockVersionPublisherMockRecorder) PublishVersion(ctx, serviceID, environment, commitRevision, branch, image, form any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishVersion", reflect.TypeOf((*MockVersionPublisher)(nil).PublishVersion), ctx, serviceID, environment, commitRevision, branch, image, form)
}

// MockBuildPublisher is a mock of BuildPublisher interface.
type MockBuildPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockBuildPublisherMockRecorder
	isgomock struct{}
}

// MockBuildPublisherMockRecorder is the mock recorder for MockBuildPublisher.
type MockBuildPublisherMockRecorder struct {
	mock *MockBuildPublisher
}

// NewMockBuildPublisher creates a new mock instance.
func NewMockBuildPublisher(ctrl *gomock.Controller) *MockBuildPublisher {
	mock := &MockBuildPublisher{ctrl: ctrl}
	mock.recorder = &MockBuildPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildPublisher) EXPECT() *MockBuildPublisherMockRecorder {
	return m.recorder
}

// PublishBuild mocks base method.
func (m *MockBuildPublisher) PublishBuild(ctx context.Context, serviceID string, request entities.BuildRequest) (*entities.Build, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishBuild", ctx, serviceID, request)
	ret0, _ := ret[0].(*entities.Build)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishBuild indicates an expected call of PublishBuild.
func (mr *MockBuildPublisherMockRecorder) PublishBuild(ctx, serviceID, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishBuild", reflect.TypeOf((*MockBuildPublisher)(nil).PublishBuild), ctx, serviceID, request)
}

// MockProtocolPublisher is a mock of ProtocolPublisher interface.
type MockProtocolPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockProtocolPublisherMockRecorder
	isgomock struct{}
}

// MockProtocolPublisherMockRecorder is the mock recorder for MockProtocolPublisher.
type MockProtocolPublisherMockRecorder struct {
	mock *MockProtocolPublisher
}

// NewMockProtocolPublisher creates a new mock instance.
func NewMockProtocolPublisher(ctrl *gomock.Controller) *MockProtocolPublisher {
	mock := &MockProtocolPublisher{ctrl: ctrl}
	mock.recorder = &MockProtocolPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProtocolPublisher) EXPECT() *MockProtocolPublisherMockRecorder {
	return m.recorder
}

// PublishProtocol mocks base method.
func (m *MockProtocolPublisher) PublishProtocol(ctx context.Context, serviceID, versionID string, format entities.ProtocolFormat, document []byte) (*entities.ProtocolPublication, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishProtocol", ctx, serviceID, versionID, format, document)
	ret0, _ := ret[0].(*entities.ProtocolPublication)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishProtocol indicates an expected call of PublishProtocol.
func (mr *MockProtocolPublisherMockRecorder) PublishProtocol(ctx, serviceID, versionID, format, document any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishProtocol", reflect.TypeOf((*MockProtocolPublisher)(nil).PublishProtocol), ctx, serviceID, versionID, format, document)
}

// MockDependencyRegistrar is a mock of DependencyRegistrar interface.
type MockDependencyRegistrar struct {
	ctrl     *gomock.Controller
	recorder *MockDependencyRegistrarMockRecorder
	isgomock struct{}
}

// MockDependencyRegistrarMockRecorder is the mock recorder for MockDependencyRegistrar.
type MockDependencyRegistrarMockRecorder struct {
	mock *MockDependencyRegistrar
}

// NewMockDependencyRegistrar creates a new mock instance.
func NewMockDependencyRegistrar(ctrl *gomock.Controller) *MockDependencyRegistrar {
	mock := &MockDependencyRegistrar{ctrl: ctrl}
	mock.recorder = &MockDependencyRegistrarMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDependencyRegistrar) EXPECT() *MockDependencyRegistrarMockRecorder {
	return m.recorder
}

// RegisterDependency mocks base method.
func (m *MockDependencyRegistrar) RegisterDependency(ctx context.Context, in DependencyRegistration) (*entities.Dependency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterDependency", ctx, in)
	ret0, _ := ret[0].(*entities.Dependency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterDependency indicates an expected call of RegisterDependency.
func (mr *MockDependencyRegistrarMockRecorder) RegisterDependency(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterDependency", reflect.TypeOf((*MockDependencyRegistrar)(nil).RegisterDependency), ctx, in)
}

// MockManifestReader is a mock of ManifestReader interface.
type MockManifestReader struct {
	ctrl     *gomock.Controller
	recorder *MockManifestReaderMockRecorder
	isgomock struct{}
}

// MockManifestReaderMockRecorder is the mock recorder for MockManifestReader.
type MockManifestReaderMockRecorder struct {
	mock *MockManifestReader
}

// NewMockManifestReader creates a new mock instance.
func NewMockManifestReader(ctrl *gomock.Controller) *MockManifestReader {
	mock := &MockManifestReader{ctrl: ctrl}
	mock.recorder = &MockManifestReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManifestReader) EXPECT() *MockManifestReaderMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockManifestReader) Read(ctx context.Context, path string) (*entities.Manifest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ctx, path)
	ret0, _ := ret[0].(*entities.Manifest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockManifestReaderMockRecorder) Read(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockManifestReader)(nil).Read), ctx, path)
}

// MockFormReader is a mock of FormReader interface.
type MockFormReader struct {
	ctrl     *gomock.Controller
	recorder *MockFormReaderMockRecorder
	isgomock struct{}
}

// MockFormReaderMockRecorder is the mock recorder for MockFormReader.
type MockFormReaderMockRecorder struct {
	mock *MockFormReader
}

// NewMockFormReader creates a new mock instance.
func NewMockFormReader(ctrl *gomock.Controller) *MockFormReader {
	mock := &MockFormReader{ctrl: ctrl}
	mock.recorder = &MockFormReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFormReader) EXPECT() *MockFormReaderMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockFormReader) Read(ctx context.Context, path string) (*entities.FormDeclaration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ctx, path)
	ret0, _ := ret[0].(*entities.FormDeclaration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockFormReaderMockRecorder) Read(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockFormReader)(nil).Read), ctx, path)
}

// MockServiceResolver is a mock of ServiceResolver interface.
type MockServiceResolver struct {
	ctrl     *gomock.Controller
	recorder *MockServiceResolverMockRecorder
	isgomock struct{}
}

// MockServiceResolverMockRecorder is the mock recorder for MockServiceResolver.
type MockServiceResolverMockRecorder struct {
	mock *MockServiceResolver
}

// NewMockServiceResolver creates a new mock instance.
func NewMockServiceResolver(ctrl *gomock.Controller) *MockServiceResolver {
	mock := &MockServiceResolver{ctrl: ctrl}
	mock.recorder = &MockServiceResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceResolver) EXPECT() *MockServiceResolverMockRecorder {
	return m.recorder
}

// ResolveIDs mocks base method.
func (m *MockServiceResolver) ResolveIDs(ctx context.Context, names []string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveIDs", ctx, names)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveIDs indicates an expected call of ResolveIDs.
func (mr *MockServiceResolverMockRecorder) ResolveIDs(ctx, names any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveIDs", reflect.TypeOf((*MockServiceResolver)(nil).ResolveIDs), ctx, names)
}

// MockCredentialAuthenticator is a mock of CredentialAuthenticator interface.
type MockCredentialAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialAuthenticatorMockRecorder
	isgomock struct{}
}

// MockCredentialAuthenticatorMockRecorder is the mock recorder for MockCredentialAuthenticator.
type MockCredentialAuthenticatorMockRecorder struct {
	mock *MockCredentialAuthenticator
}

// NewMockCredentialAuthenticator creates a new mock instance.
func NewMockCredentialAuthenticator(ctrl *gomock.Controller) *MockCredentialAuthenticator {
	mock := &MockCredentialAuthenticator{ctrl: ctrl}
	mock.recorder = &MockCredentialAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialAuthenticator) EXPECT() *MockCredentialAuthenticatorMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockCredentialAuthenticator) Authenticate(ctx context.Context, email, password string) (*entities.UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, email, password)
	ret0, _ := ret[0].(*entities.UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockCredentialAuthenticatorMockRecorder) Authenticate(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockCredentialAuthenticator)(nil).Authenticate), ctx, email, password)
}

// MockSessionInspector is a mock of SessionInspector interface.
type MockSessionInspector struct {
	ctrl     *gomock.Controller
	recorder *MockSessionInspectorMockRecorder
	isgomock struct{}
}

// MockSessionInspectorMockRecorder is the mock recorder for MockSessionInspector.
type MockSessionInspectorMockRecorder struct {
	mock *MockSessionInspector
}

// NewMockSessionInspector creates a new mock instance.
func NewMockSessionInspector(ctrl *gomock.Controller) *MockSessionInspector {
	mock := &MockSessionInspector{ctrl: ctrl}
	mock.recorder = &MockSessionInspectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionInspector) EXPECT() *MockSessionInspectorMockRecorder {
	return m.recorder
}

// Inspect mocks base method.
func (m *MockSessionInspector) Inspect(ctx context.Context, token string) (*entities.UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inspect", ctx, token)
	ret0, _ := ret[0].(*entities.UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inspect indicates an expected call of Inspect.
func (mr *MockSessionInspectorMockRecorder) Inspect(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inspect", reflect.TypeOf((*MockSessionInspector)(nil).Inspect), ctx, token)
}

// MockSessionRevoker is a mock of SessionRevoker interface.
type MockSessionRevoker struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRevokerMockRecorder
	isgomock struct{}
}

// MockSessionRevokerMockRecorder is the mock recorder for MockSessionRevoker.
type MockSessionRevokerMockRecorder struct {
	mock *MockSessionRevoker
}

// NewMockSessionRevoker creates a new mock instance.
func NewMockSessionRevoker(ctrl *gomock.Controller) *MockSessionRevoker {
	mock := &MockSessionRevoker{ctrl: ctrl}
	mock.recorder = &MockSessionRevokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRevoker) EXPECT() *MockSessionRevokerMockRecorder {
	return m.recorder
}

// Revoke mocks base method.
func (m *MockSessionRevoker) Revoke(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockSessionRevokerMockRecorder) Revoke(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockSessionRevoker)(nil).Revoke), ctx, token)
}

// MockSessionStore is a mock of SessionStore interface.
type MockSessionStore struct {
	ctrl     *gomock.Controller
	recorder *MockSessionStoreMockRecorder
	isgomock struct{}
}

// MockSessionStoreMockRecorder is the mock recorder for MockSessionStore.
type MockSessionStoreMockRecorder struct {
	mock *MockSessionStore
}

// NewMockSessionStore creates a new mock instance.
func NewMockSessionStore(ctrl *gomock.Controller) *MockSessionStore {
	mock := &MockSessionStore{ctrl: ctrl}
	mock.recorder = &MockSessionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionStore) EXPECT() *MockSessionStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSessionStore) Delete(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionStoreMockRecorder) Delete(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionStore)(nil).Delete), ctx)
}

// Load mocks base method.
func (m *MockSessionStore) Load(ctx context.Context) (*entities.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx)
	ret0, _ := ret[0].(*entities.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockSessionStoreMockRecorder) Load(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockSessionStore)(nil).Load), ctx)
}

// Save mocks base method.
func (m *MockSessionStore) Save(ctx context.Context, credential entities.Credential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, credential)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSessionStoreMockRecorder) Save(ctx, credential any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSessionStore)(nil).Save), ctx, credential)
}

// MockBrowserAuthorizer is a mock of BrowserAuthorizer interface.
type MockBrowserAuthorizer struct {
	ctrl     *gomock.Controller
	recorder *MockBrowserAuthorizerMockRecorder
	isgomock struct{}
}

// MockBrowserAuthorizerMockRecorder is the mock recorder for MockBrowserAuthorizer.
type MockBrowserAuthorizerMockRecorder struct {
	mock *MockBrowserAuthorizer
}

// NewMockBrowserAuthorizer creates a new mock instance.
func NewMockBrowserAuthorizer(ctrl *gomock.Controller) *MockBrowserAuthorizer {
	mock := &MockBrowserAuthorizer{ctrl: ctrl}
	mock.recorder = &MockBrowserAuthorizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrowserAuthorizer) EXPECT() *MockBrowserAuthorizerMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *MockBrowserAuthorizer) Authorize(ctx context.Context) (*entities.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", ctx)
	ret0, _ := ret[0].(*entities.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorize indicates an expected call of Authorize.
func (mr *MockBrowserAuthorizerMockRecorder) Authorize(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockBrowserAuthorizer)(nil).Authorize), ctx)
}

// MockPersonalTokenDirectory is a mock of PersonalTokenDirectory interface.
type MockPersonalTokenDirectory struct {
	ctrl     *gomock.Controller
	recorder *MockPersonalTokenDirectoryMockRecorder
	isgomock struct{}
}

// MockPersonalTokenDirectoryMockRecorder is the mock recorder for MockPersonalTokenDirectory.
type MockPersonalTokenDirectoryMockRecorder struct {
	mock *MockPersonalTokenDirectory
}

// NewMockPersonalTokenDirectory creates a new mock instance.
func NewMockPersonalTokenDirectory(ctrl *gomock.Controller) *MockPersonalTokenDirectory {
	mock := &MockPersonalTokenDirectory{ctrl: ctrl}
	mock.recorder = &MockPersonalTokenDirectoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersonalTokenDirectory) EXPECT() *MockPersonalTokenDirectoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockPersonalTokenDirectory) List(ctx context.Context) ([]entities.PersonalToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entities.PersonalToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPersonalTokenDirectoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPersonalTokenDirectory)(nil).List), ctx)
}

// Revoke mocks base method.
func (m *MockPersonalTokenDirectory) Revoke(ctx context.Context, tokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockPersonalTokenDirectoryMockRecorder) Revoke(ctx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockPersonalTokenDirectory)(nil).Revoke), ctx, tokenID)
}
