// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TraumTech/paas-cli/internal/controllers/build_publish_command_cli (interfaces: BuildPublisher)
//
// Generated by this command:
//
//	mockgen -destination=dependencies_mock_test.go -package=buildpublishcommandcli github.com/TraumTech/paas-cli/internal/controllers/build_publish_command_cli BuildPublisher
//

// Package buildpublishcommandcli is a generated GoMock package.
package buildpublishcommandcli

import (
	context "context"
	reflect "reflect"

	entities "github.com/TraumTech/paas-cli/internal/entities"
	usecases "github.com/TraumTech/paas-cli/internal/usecases"
	gomock "go.uber.org/mock/gomock"
)

// MockBuildPublisher is a mock of BuildPublisher interface.
type MockBuildPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockBuildPublisherMockRecorder
	isgomock struct{}
}

// MockBuildPublisherMockRecorder is the mock recorder for MockBuildPublisher.
type MockBuildPublisherMockRecorder struct {
	mock *MockBuildPublisher
}

// NewMockBuildPublisher creates a new mock instance.
func NewMockBuildPublisher(ctrl *gomock.Controller) *MockBuildPublisher {
	mock := &MockBuildPublisher{ctrl: ctrl}
	mock.recorder = &MockBuildPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildPublisher) EXPECT() *MockBuildPublisherMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockBuildPublisher) Execute(ctx context.Context, in usecases.PublishBuildInput) (*entities.Build, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*entities.Build)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockBuildPublisherMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockBuildPublisher)(nil).Execute), ctx, in)
}
