// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TraumTech/paas-cli/internal/controllers/protocol_sync_command_cli (interfaces: ProtocolSyncer)
//
// Generated by this command:
//
//	mockgen -destination=dependencies_mock_test.go -package=protocolsynccommandcli github.com/TraumTech/paas-cli/internal/controllers/protocol_sync_command_cli ProtocolSyncer
//

// Package protocolsynccommandcli is a generated GoMock package.
package protocolsynccommandcli

import (
	context "context"
	reflect "reflect"

	usecases "github.com/TraumTech/paas-cli/internal/usecases"
	gomock "go.uber.org/mock/gomock"
)

// MockProtocolSyncer is a mock of ProtocolSyncer interface.
type MockProtocolSyncer struct {
	ctrl     *gomock.Controller
	recorder *MockProtocolSyncerMockRecorder
	isgomock struct{}
}

// MockProtocolSyncerMockRecorder is the mock recorder for MockProtocolSyncer.
type MockProtocolSyncerMockRecorder struct {
	mock *MockProtocolSyncer
}

// NewMockProtocolSyncer creates a new mock instance.
func NewMockProtocolSyncer(ctrl *gomock.Controller) *MockProtocolSyncer {
	mock := &MockProtocolSyncer{ctrl: ctrl}
	mock.recorder = &MockProtocolSyncerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProtocolSyncer) EXPECT() *MockProtocolSyncerMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockProtocolSyncer) Execute(ctx context.Context, in usecases.SyncProtocolsInput) (*usecases.SyncProtocolsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*usecases.SyncProtocolsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockProtocolSyncerMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockProtocolSyncer)(nil).Execute), ctx, in)
}
