// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TraumTech/paas-cli/internal/controllers/auth_login_command_cli (interfaces: UserLogin,BrowserLogin)
//
// Generated by this command:
//
//	mockgen -destination=dependencies_mock_test.go -package=authlogincommandcli github.com/TraumTech/paas-cli/internal/controllers/auth_login_command_cli UserLogin,BrowserLogin
//

// Package authlogincommandcli is a generated GoMock package.
package authlogincommandcli

import (
	context "context"
	reflect "reflect"

	usecases "github.com/TraumTech/paas-cli/internal/usecases"
	gomock "go.uber.org/mock/gomock"
)

// MockUserLogin is a mock of UserLogin interface.
type MockUserLogin struct {
	ctrl     *gomock.Controller
	recorder *MockUserLoginMockRecorder
	isgomock struct{}
}

// MockUserLoginMockRecorder is the mock recorder for MockUserLogin.
type MockUserLoginMockRecorder struct {
	mock *MockUserLogin
}

// NewMockUserLogin creates a new mock instance.
func NewMockUserLogin(ctrl *gomock.Controller) *MockUserLogin {
	mock := &MockUserLogin{ctrl: ctrl}
	mock.recorder = &MockUserLoginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserLogin) EXPECT() *MockUserLoginMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUserLogin) Execute(ctx context.Context, in usecases.LoginInput) (*usecases.LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*usecases.LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockUserLoginMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUserLogin)(nil).Execute), ctx, in)
}

// MockBrowserLogin is a mock of BrowserLogin interface.
type MockBrowserLogin struct {
	ctrl     *gomock.Controller
	recorder *MockBrowserLoginMockRecorder
	isgomock struct{}
}

// MockBrowserLoginMockRecorder is the mock recorder for MockBrowserLogin.
type MockBrowserLoginMockRecorder struct {
	mock *MockBrowserLogin
}

// NewMockBrowserLogin creates a new mock instance.
func NewMockBrowserLogin(ctrl *gomock.Controller) *MockBrowserLogin {
	mock := &MockBrowserLogin{ctrl: ctrl}
	mock.recorder = &MockBrowserLoginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrowserLogin) EXPECT() *MockBrowserLoginMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockBrowserLogin) Execute(ctx context.Context) (*usecases.BrowserLoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx)
	ret0, _ := ret[0].(*usecases.BrowserLoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockBrowserLoginMockRecorder) Execute(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockBrowserLogin)(nil).Execute), ctx)
}
