// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TraumTech/paas-cli/internal/controllers/database_operator_install_command_cli (interfaces: OperatorInstaller)
//
// Generated by this command:
//
//	mockgen -destination=dependencies_mock_test.go -package=databaseoperatorinstallcommandcli github.com/TraumTech/paas-cli/internal/controllers/database_operator_install_command_cli OperatorInstaller
//

// Package databaseoperatorinstallcommandcli is a generated GoMock package.
package databaseoperatorinstallcommandcli

import (
	context "context"
	reflect "reflect"

	usecases "github.com/TraumTech/paas-cli/internal/usecases"
	gomock "go.uber.org/mock/gomock"
)

// MockOperatorInstaller is a mock of OperatorInstaller interface.
type MockOperatorInstaller struct {
	ctrl     *gomock.Controller
	recorder *MockOperatorInstallerMockRecorder
	isgomock struct{}
}

// MockOperatorInstallerMockRecorder is the mock recorder for MockOperatorInstaller.
type MockOperatorInstallerMockRecorder struct {
	mock *MockOperatorInstaller
}

// NewMockOperatorInstaller creates a new mock instance.
func NewMockOperatorInstaller(ctrl *gomock.Controller) *MockOperatorInstaller {
	mock := &MockOperatorInstaller{ctrl: ctrl}
	mock.recorder = &MockOperatorInstallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperatorInstaller) EXPECT() *MockOperatorInstallerMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockOperatorInstaller) Execute(ctx context.Context, input usecases.InstallOperatorInput, confirm usecases.InstallOperatorConfirmFunc) (*usecases.InstallOperatorResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input, confirm)
	ret0, _ := ret[0].(*usecases.InstallOperatorResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockOperatorInstallerMockRecorder) Execute(ctx, input, confirm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockOperatorInstaller)(nil).Execute), ctx, input, confirm)
}
