// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TraumTech/paas-cli/internal/controllers/auth_whoami_command_cli (interfaces: CurrentUser)
//
// Generated by this command:
//
//	mockgen -destination=dependencies_mock_test.go -package=authwhoamicommandcli github.com/TraumTech/paas-cli/internal/controllers/auth_whoami_command_cli CurrentUser
//

// Package authwhoamicommandcli is a generated GoMock package.
package authwhoamicommandcli

import (
	context "context"
	reflect "reflect"

	usecases "github.com/TraumTech/paas-cli/internal/usecases"
	gomock "go.uber.org/mock/gomock"
)

// MockCurrentUser is a mock of CurrentUser interface.
type MockCurrentUser struct {
	ctrl     *gomock.Controller
	recorder *MockCurrentUserMockRecorder
	isgomock struct{}
}

// MockCurrentUserMockRecorder is the mock recorder for MockCurrentUser.
type MockCurrentUserMockRecorder struct {
	mock *MockCurrentUser
}

// NewMockCurrentUser creates a new mock instance.
func NewMockCurrentUser(ctrl *gomock.Controller) *MockCurrentUser {
	mock := &MockCurrentUser{ctrl: ctrl}
	mock.recorder = &MockCurrentUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCurrentUser) EXPECT() *MockCurrentUserMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCurrentUser) Execute(ctx context.Context) (*usecases.WhoAmIResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx)
	ret0, _ := ret[0].(*usecases.WhoAmIResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCurrentUserMockRecorder) Execute(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCurrentUser)(nil).Execute), ctx)
}
